/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.12 bath2.glb
*/

import React, { useRef, forwardRef } from 'react';
import { useGLTF } from '@react-three/drei';

const Bath2 = forwardRef(({ events, props, action, rotate, color }, ref) => {
  const { nodes, materials } = useGLTF('/bath2.glb')
  return (
    <group
      dispose={null}
      {...props}
      {...events}
      ref={ref}
      onClick={action}
      rotation-y={rotate}
    >
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.Object_2.geometry} material={materials.bottom} material-color={color.Body ? color.Body : null}/>
        <mesh geometry={nodes.Object_3.geometry} material={materials.m_glass_door} material-color={color.Glass ? color.Glass : null}/>
        <mesh geometry={nodes.Object_4.geometry} material={materials.m_shower} material-color={color.Shower ? color.Shower : null}/>
        <mesh geometry={nodes.Object_6.geometry} material={materials.m_walls_frame_handle_drain} material-color={color.Body ? color.Body : null}/>
      </group>
    </group>
  )
});

useGLTF.preload('/bath2.glb');

export default Bath2;
