/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.12 bath7.glb
*/

import React, { useRef, forwardRef } from 'react';
import { useGLTF } from '@react-three/drei';

const Bath7 = forwardRef(({ events, props, action, rotate, color }, ref) => {
  const { nodes, materials } = useGLTF('/bath7.glb')
  return (
    <group
      dispose={null}
      {...props}
      {...events}
      ref={ref}
      onClick={action}
      rotation-y={rotate}
    >
      <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
        <mesh geometry={nodes['Vaal_VAA-772662WH_Chrome_0'].geometry} material={materials.Chrome} material-color={color.Body ? color.Body : null}/>
        <mesh geometry={nodes['Vaal_VAA-772662WH_Matt_Black_0'].geometry} material={materials.Matt_Black} material-color={color.Body ? color.Body : null}/>
        <mesh geometry={nodes['Vaal_VAA-772662WH_White_ceramic_0'].geometry} material={materials.White_ceramic} material-color={color.Body ? color.Body : null}/>
      </group>
    </group>
  )
});

useGLTF.preload('/bath7.glb');

export default Bath7;
