/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.12 bath5.glb
*/

import React, { useRef, forwardRef } from 'react';
import { useGLTF } from '@react-three/drei';

const Bath5 = forwardRef(({ events, props, action, rotate, color }, ref) => {
  const { nodes, materials } = useGLTF('/bath5.glb')
  return (
    <group
      dispose={null}
      {...props}
      {...events}
      ref={ref}
      onClick={action}
      rotation-y={rotate}
    >
      <mesh geometry={nodes['Object001_01_-_Default_0'].geometry} material={materials['01_-_Default']} rotation={[-Math.PI / 2, 0, 0]} material-color={color.Body ? color.Body : null}/>
    </group>
  )
});

useGLTF.preload('/bath5.glb');

export default Bath5;
