/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.12 bath6.glb
*/

import React, { useRef, forwardRef } from 'react';
import { useGLTF } from '@react-three/drei';

const Bath6 = forwardRef(({ events, props, action, rotate, color }, ref) => {
  const { nodes, materials } = useGLTF('/bath6.glb')
  return (
    <group
      dispose={null}
      {...props}
      {...events}
      ref={ref}
      onClick={action}
      rotation-y={rotate}
    >
      <group scale={0.01}>
        <mesh geometry={nodes.Drain_Chrome_light_0.geometry} material={materials.Chrome_light} material-color={color.Drain ? color.Drain : null}/>
        <mesh geometry={nodes.Handles_Chrome_dark_0.geometry} material={materials.Chrome_dark} />
        <mesh geometry={nodes.Main_dark_0.geometry} material={materials.dark} material-color={color.Main ? color.Main : null}/>
        <mesh geometry={nodes.Sink_dark_0.geometry} material={materials.dark} material-color={color.Sink ? color.Sink : null}/>
        <mesh geometry={nodes.Table_wood_0.geometry} material={materials.wood} material-color={color.Table ? color.Table : null}/>
        <mesh geometry={nodes.Tap_Chrome_dark_0.geometry} material={materials.Chrome_dark} />
        <mesh geometry={nodes.Tap_Chrome_light_0.geometry} material={materials.Chrome_light} />
      </group>
    </group>
  )
});

useGLTF.preload('/bath6.glb');

export default Bath6;
