/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.12 bath1.glb
*/

import React, { useRef, forwardRef } from 'react';
import { useGLTF } from '@react-three/drei';

const Bath1 = forwardRef(({ events, props, action, rotate, color }, ref) => {
  const { nodes, materials } = useGLTF('/bath1.glb')
  return (
    <group
      dispose={null}
      {...props}
      {...events}
      ref={ref}
      onClick={action}
      rotation-y={rotate}
    >
      <group position={[-0.808, 0, -0.639]}>
        <group position={[0, 0.164, 0.341]}>
          <mesh geometry={nodes.Object_10.geometry} material={materials.Chrome} />
          <mesh geometry={nodes.Object_11.geometry} material={materials.Black} />
        </group>
        <group position={[-0.306, 0.31, 0.214]}>
          <mesh geometry={nodes.Object_15.geometry} material={materials['Glass.002']} />
          <mesh geometry={nodes.Object_17.geometry} material={materials.Creme} position={[0, -0.018, 0]} />
        </group>
        <group position={[0.791, 0.298, -0.025]}>
          <group position={[0.027, -0.339, -0.027]}>
            <mesh geometry={nodes.Object_28.geometry} material={materials['Material.003']} />
            <mesh geometry={nodes.Object_29.geometry} material={materials['Material.003']} />
          </group>
          <mesh geometry={nodes.Object_25.geometry} material={materials['Material.003']} />
          <mesh geometry={nodes.Object_26.geometry} material={materials['Material.004']} />
        </group>
        <group position={[-0.316, 0.325, -0.251]}>
          <mesh geometry={nodes.Object_35.geometry} material={materials.Wine_Glass} />
          <mesh geometry={nodes.Object_36.geometry} material={materials.Red_Wine} />
        </group>
        <mesh geometry={nodes.Object_4.geometry} material={materials.bathtub} material-color={color.Body ? color.Body : null}/>
        <mesh geometry={nodes.Object_6.geometry} material={materials.Wood} position={[-0.308, 0.263, 0.011]} />
        <mesh geometry={nodes.Object_8.geometry} material={materials.Chrome} position={[0, -0.164, 0.203]} />
        <mesh geometry={nodes.Object_13.geometry} material={materials.bathtub} position={[-0.319, 0.285, -0.111]} />
        <mesh geometry={nodes.Object_19.geometry} material={materials['Creme.002']} position={[-0.318, 0.296, -0.113]} />
        <mesh geometry={nodes.Object_21.geometry} material={materials.cover} position={[-0.306, 0.353, 0.214]} />
        <mesh geometry={nodes.Object_23.geometry} material={materials.fabric} position={[-0.049, 0.031, -0.377]} />
        <mesh geometry={nodes.Object_33.geometry} material={materials.material} position={[-0.311, 0.405, 0.124]} />
        <mesh geometry={nodes.Object_31.geometry} material={materials.material} position={[-0.31, 0.382, 0.025]} />
      </group>
    </group>
  )
});

useGLTF.preload('/bath1.glb');

export default Bath1;
