/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.12 bath3.glb
*/

import React, { useRef, forwardRef } from 'react';
import { useGLTF } from '@react-three/drei';

const Bath3 = forwardRef(({ events, props, action, rotate, color }, ref) => {
  const { nodes, materials } = useGLTF('/bath3.glb')
  return (
    <group
      dispose={null}
      {...props}
      {...events}
      ref={ref}
      onClick={action}
      rotation-y={rotate}
    >
      <group rotation={[-Math.PI / 2, 0, 0]} scale={0.003}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <group position={[0.003, 399.71, -81.591]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <mesh geometry={nodes.Circle001_Diffuse_0.geometry} material={materials.Diffuse} />
            <mesh geometry={nodes.Circle001_Goma_0.geometry} material={materials.Goma} />
            <mesh geometry={nodes.Circle001_Metal_0.geometry} material={materials.Metal} />
          </group>
          <mesh geometry={nodes.Cube_Ceramica_0.geometry} material={materials.Ceramica} position={[0, 297.832, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={100} material-color={color.Body ? color.Body : null}/>
        </group>
      </group>
    </group>
  )
});

useGLTF.preload('/bath3.glb');

export default Bath3;
