/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.12 bath9.glb
*/

import React, { useRef, forwardRef } from 'react';
import { useGLTF } from '@react-three/drei';

const Bath9 = forwardRef(({ events, props, action, rotate, color }, ref) => {
  const { nodes, materials } = useGLTF('/bath9.glb')
  return (
    <group
      dispose={null}
      {...props}
      {...events}
      ref={ref}
      onClick={action}
      rotation-y={rotate}
    >
      <mesh geometry={nodes.Object_6.geometry} material={materials['Scene_-_Root']} position={[-0.505, 0.86, 0]} scale={[0.026, 0.026, 0.299]} material-color={color.Body ? color.Body : null}/>
      <mesh geometry={nodes.Object_10.geometry} material={materials['Scene_-_Root']} position={[0.46, 0.912, 0]} rotation={[0, 0, -Math.PI / 2]} scale={[0.026, 0.014, 0.299]} material-color={color.Body ? color.Body : null}/>
      <mesh geometry={nodes.Object_8.geometry} material={materials['Scene_-_Root']} position={[0.46, -0.981, 0]} rotation={[0, 0, -Math.PI / 2]} scale={[0.026, 0.014, 0.299]} material-color={color.Body ? color.Body : null}/>
      <mesh geometry={nodes.Object_12.geometry} material={materials['Scene_-_Root']} position={[0.412, 0.43, 0]} scale={[0.009, 0.009, 0.299]} material-color={color.Body ? color.Body : null}/>
      <mesh geometry={nodes.Object_14.geometry} material={materials['Scene_-_Root']} position={[0.412, -0.499, 0]} scale={[0.009, 0.009, 0.299]} material-color={color.Body ? color.Body : null}/>
      <mesh geometry={nodes.Object_16.geometry} material={materials['Scene_-_Root']} position={[0.412, -0.036, 0]} scale={[0.009, 0.009, 0.299]} material-color={color.Body ? color.Body : null}/>
      <mesh geometry={nodes.Object_4.geometry} material={materials['Scene_-_Root']} position={[0.448, 0.86, 0]} rotation={[0, 0, -Math.PI]} scale={[-0.026, -0.026, -0.299]} material-color={color.Body ? color.Body : null}/>
    </group>
  )
});

useGLTF.preload('/bath9.glb');

export default Bath9;
