import { createContext, useContext, useState } from 'react';

import {
	Bed1,
	Bed2,
	Bed3,
	Bed4,
	Bed5,
	Bed6,
	Bed7,
	Bed8,
	Bed9,
	Living1,
	Living2,
	Living3,
	Living4,
	Living5,
	Living6,
	Living7,
	Living8,
	Living9,
	Kitchen1,
	Kitchen2,
	Kitchen3,
	Kitchen4,
	Kitchen5,
	Kitchen6,
	Kitchen7,
	Kitchen8,
	Kitchen9,
	Dining1,
	Dining2,
	Dining3,
	Dining4,
	Dining5,
	Dining6,
	Dining7,
	Dining8,
	Dining9,
	Bath1,
	Bath2,
	Bath3,
	Bath4,
	Bath5,
	Bath6,
	Bath7,
	Bath8,
	Bath9,
} from './src/assets';

const FurnitureContext = createContext({});

export const FurnitureProvider = (props) => {
	const [activeFurn, setActiveFurn] = useState([]);

	//bedroom models
	const [kitchenFurn, setKitchenFurn] = useState([
		{
			key: 0,
			name: 'Top Freezer Refrigerator',
			img: 'https://i.imgur.com/PsA1PM1.png',
			model: <Kitchen1 />,
			w: 30,
			l: 30,
			rotation: 0,
			isActive: false,
			isShown: false,
			color: {
				Body: null,
			},
			xMin: -5.4,
			xMax: 5.5,
			zMin: -4.5,
			zMax: 5.5,
		},
		{
			key: 1,
			name: 'Double Stove',
			img: 'https://i.imgur.com/fG7Wsiq.png',
			model: <Kitchen2 />,
			w: 45.2,
			l: 36.1,
			rotation: 0,
			isActive: false,
			isShown: false,
			color: {
				Back: null,
				Window: null,
				Box: null,
				Stove: null,
			},
			xMin: -5.4,
			xMax: 5.5,
			zMin: -4.5,
			zMax: 5.5,
		},
		{
			key: 2,
			name: 'Wall-Mounted Kitchen Storage',
			img: 'https://i.imgur.com/tVQqZJb.png',
			model: <Kitchen3 />,
			w: 30.3,
			l: 21.1,
			rotation: 0,
			isActive: false,
			isShown: false,
			color: {
				Shelves: null,
				Box: null,
			},
			xMin: -5.4,
			xMax: 5.5,
			zMin: -4.5,
			zMax: 5.5,
		},

		{
			key: 3,
			name: 'Tall Kitchen Table',
			img: 'https://i.imgur.com/LXE2I7y.png',
			model: <Kitchen4 />,
			w: 19.4,
			l: 40.3,
			rotation: 0,
			isActive: false,
			isShown: false,
			color: {
				Color: null,
			},
			xMin: -5.4,
			xMax: 5.5,
			zMin: -4.5,
			zMax: 5.5,
		},

		{
			key: 4,
			name: 'Corner Kitchen Sink with Stove',
			img: 'https://i.imgur.com/RFfMvnh.png',
			model: <Kitchen5 />,
			w: 90.3,
			l: 68.5,
			rotation: 0,
			isActive: false,
			isShown: false,
			color: {
				Color: null,
				Stove: null,
				Sink: null,
			},
			xMin: -5.4,
			xMax: 5.5,
			zMin: -4.5,
			zMax: 5.5,
		},
		{
			key: 5,
			name: 'Small Kitchen Cabinet',
			img: 'https://i.imgur.com/UiXyK8A.png',
			model: <Kitchen6 />,
			w: 17.6,
			l: 30,
			rotation: 0,
			isActive: false,
			isShown: false,
			color: {
				Color: null,
				Handle: null,
			},
			xMin: -5.4,
			xMax: 5.5,
			zMin: -4.5,
			zMax: 5.5,
		},
		{
			key: 6,
			name: 'Long Kitchen Cabinet',
			img: 'https://i.imgur.com/CKLfgDE.png',
			model: <Kitchen7 />,
			w: 82.1,
			l: 29,
			rotation: 0,
			isActive: false,
			isShown: false,
			color: {
				Color: null,
			},
			xMin: -5.4,
			xMax: 5.5,
			zMin: -4.5,
			zMax: 5.5,
		},
		{
			key: 7,
			name: 'Small Kitchen Sink',
			img: 'https://i.imgur.com/h1EzWtC.png',
			model: <Kitchen8 />,
			w: 39.2,
			l: 32.6,
			rotation: 0,
			isActive: false,
			isShown: false,
			color: {
				Color: null,
				Handle: null,
				Sink: null,
			},
			xMin: -5.4,
			xMax: 5.5,
			zMin: -4.5,
			zMax: 5.5,
		},
		{
			key: 8,
			name: 'Small oven with stove',
			img: 'https://i.imgur.com/yDKHpvX.png',
			model: <Kitchen9 />,
			w: 30.4,
			l: 27.2,
			rotation: 0,
			isActive: false,
			isShown: false,
			color: {
				Color: null,
			},
			xMin: -5.4,
			xMax: 5.5,
			zMin: -4.5,
			zMax: 5.5,
		},
	]);
	//diningroom models
	const [diningRoomFurn, setDiningRoomFurn] = useState([
		{
			key: 0,
			name: 'Breakfast Bar',
			img: 'https://i.imgur.com/rgiz093.png',
			model: <Dining1 />,
			w: 58.2,
			l: 43.1,
			rotation: 0,
			isActive: false,
			isShown: false,
			color: {
				Body: null,
				Chair: null,
				Legs: null,
			},
			xMin: -5.4,
			xMax: 5.5,
			zMin: -4.5,
			zMax: 5.5,
		},

		{
			key: 1,
			name: 'Small Dining Table Set',
			img: 'https://i.imgur.com/fNzqKn7.png',
			model: <Dining2 />,
			w: 35.5,
			l: 31.4,
			rotation: 0,
			isActive: false,
			isShown: false,
			color: {
				Table: null,
				Chair: null,
			},
			xMin: -5.4,
			xMax: 5.5,
			zMin: -4.5,
			zMax: 5.5,
		},
		{
			key: 2,
			name: 'Big Dining Table Set',
			img: 'https://i.imgur.com/jpVH2pF.png',
			model: <Dining3 />,
			w: 88.2,
			l: 31,
			rotation: 0,
			isActive: false,
			isShown: false,
			color: {
				Table: null,
				Chair: null,
			},
			xMin: -5.4,
			xMax: 5.5,
			zMin: -4.5,
			zMax: 5.5,
		},

		{
			key: 3,
			name: 'Dining Cabinet',
			img: 'https://i.imgur.com/Bx8FAzc.png',
			model: <Dining4 />,
			w: 45,
			l: 33,
			rotation: 0,
			isActive: false,
			isShown: false,
			color: {
				Body: null,
			},
			xMin: -5.4,
			xMax: 5.5,
			zMin: -4.5,
			zMax: 5.5,
		},

		{
			key: 4,
			name: 'Single Dining Chair',
			img: 'https://i.imgur.com/9pulonv.png',
			model: <Dining5 />,
			w: 15.3,
			l: 30,
			rotation: 0,
			isActive: false,
			isShown: false,
			color: {
				Body: null,
			},
			xMin: -5.4,
			xMax: 5.5,
			zMin: -4.5,
			zMax: 5.5,
		},
		{
			key: 5,
			name: 'Round Table',
			img: 'https://i.imgur.com/W5vyZ3T.png',
			model: <Dining6 />,
			w: 28,
			l: 24,
			rotation: 0,
			isActive: false,
			isShown: false,
			color: {
				Body: null,
			},
			xMin: -5.4,
			xMax: 5.5,
			zMin: -4.5,
			zMax: 5.5,
		},
		{
			key: 6,
			name: 'Marble Table',
			img: 'https://i.imgur.com/oEtAJIv.png',
			model: <Dining7 />,
			w: 32,
			l: 28.1,
			rotation: 0,
			isActive: false,
			isShown: false,
			color: {
				Table: null,
				Stand: null,
			},
			xMin: -5.4,
			xMax: 5.5,
			zMin: -4.5,
			zMax: 5.5,
		},

		{
			key: 7,
			name: 'Single Dining Chair',
			img: 'https://i.imgur.com/gs9YRgi.png',
			model: <Dining8 />,
			w: 15,
			l: 30.3,
			rotation: 0,
			isActive: false,
			isShown: false,
			color: {
				Seat: null,
				Stand: null,
			},
			xMin: -5.4,
			xMax: 5.5,
			zMin: -4.5,
			zMax: 5.5,
		},
		{
			key: 8,
			name: 'Hutch',
			img: 'https://i.imgur.com/zPhFziB.png',
			model: <Dining9 />,
			w: 26.5,
			l: 48.1,
			rotation: 0,
			isActive: false,
			isShown: false,
			color: {
				Body: null,
			},
			xMin: -5.4,
			xMax: 5.5,
			zMin: -4.5,
			zMax: 5.5,
		},
	]);
	//bedroom models
	const [bedroomFurn, setBedroom] = useState([
		{
			key: 0,
			name: 'Wooden Bed',
			img: 'https://i.imgur.com/0j6WDfe.png',
			model: <Bed1 />,
			w: 60,
			l: 80,
			rotation: 0,
			isActive: false,
			isShown: false,
			color: {
				Mattress: null,
				Pillows: null,
				Sheet: null,
				Board: null,
			},
			xMin: -5.4,
			xMax: 5.5,
			zMin: 5.5,
			zMax: 5.5,
		},
		{
			key: 1,
			name: 'Bed with Side Table',
			img: 'https://i.imgur.com/974HQQl.png',
			model: <Bed2 />,
			w: 80,
			l: 80,
			rotation: 0,
			isActive: false,
			isShown: false,
			color: {
				Mattress: null,
				Board: null,
			},
			xMin: -5.4,
			xMax: 5.5,
			zMin: 5.5,
			zMax: 5.5,
		},
		{
			key: 2,
			name: 'Bed with Steel Board',
			img: 'https://i.imgur.com/hV1gQvk.png',
			model: <Bed3 />,
			w: 39,
			l: 80,
			rotation: 0,
			isActive: false,
			isShown: false,
			color: {
				Mattress: null,
				Pillows: null,
				Sheet: null,
				Board: null,
			},
			xMin: -5.4,
			xMax: 5.5,
			zMin: -4.5,
			zMax: 5.5,
		},
		{
			key: 3,
			name: 'Bed with Head Board',
			img: 'https://i.imgur.com/R9Eh8Tc.png',
			model: <Bed4 />,
			w: 60,
			l: 80,
			rotation: 0,
			isActive: false,
			isShown: false,
			color: {
				Mattress: null,
				Pillows: null,
				Sheet: null,
				Board: null,
			},
			xMin: -5.4,
			xMax: 5.5,
			zMin: -0.3,
			zMax: 0.2,
		},

		{
			key: 4,
			name: 'Long Bed',
			img: 'https://i.imgur.com/0dO9jnQ.png',
			model: <Bed5 />,
			w: 40,
			l: 80,

			rotation: 0,
			isActive: false,
			isShown: false,
			color: {
				Sheet: null,
				Board: null,
			},
			xMin: -5.4,
			xMax: 5.5,
			zMin: -4.5,
			zMax: 5.5,
		},
		{
			key: 5,
			name: 'Double Decker Bed',
			img: 'https://i.imgur.com/GKu2uak.png',
			model: <Bed6 />,
			w: 55,
			l: 80,

			rotation: 0,
			isActive: false,
			isShown: false,
			color: {
				Color: null,
			},
			xMin: -5.4,
			xMax: 5.5,
			zMin: -4.5,
			zMax: 5.5,
		},
		{
			key: 6,
			name: 'Bed with Two Side Table',
			img: 'https://i.imgur.com/J1tKQFy.png',
			model: <Bed7 />,
			w: 52,
			l: 80,

			rotation: 0,
			isActive: false,
			isShown: false,
			color: {
				Mattress: null,
				Body: null,
				Pillow: null,
			},
			xMin: -5.4,
			xMax: 5.5,
			zMin: -4.5,
			zMax: 5.5,
		},
		{
			key: 7,
			name: 'Luxury Bed',
			img: 'https://i.imgur.com/4qHfZFo.png',
			model: <Bed8 />,
			w: 60,
			l: 80,

			rotation: 0,
			isActive: false,
			isShown: false,
			color: {
				Blanket: null,
				Body: null,
				Mattress: null,
			},
			xMin: -5.4,
			xMax: 5.5,
			zMin: -4.5,
			zMax: 5.5,
		},
		{
			key: 8,
			name: 'Round Bed',
			img: 'https://i.imgur.com/731sWYO.png',
			model: <Bed9 />,
			w: 46,
			l: 80,

			rotation: 0,
			isActive: false,
			isShown: false,
			color: {
				Blanket: null,
				Mattress: null,
				Sheet: null,
				Wood: null,
				Pillow: null,
			},
			xMin: -5.4,
			xMax: 5.5,
			zMin: -4.5,
			zMax: 5.5,
		},
	]);
	//livingroom models
	const [livingroomFurn, setLivingroom] = useState([
		{
			key: 0,
			name: 'Double seat Couch',
			img: 'https://i.imgur.com/CtQb8D0.png',
			model: <Living1 />,
			w: 80.2,
			l: 30.1,
			rotation: 0,
			isActive: false,
			isShown: false,
			color: {
				Sofa: null,
			},
			xMin: -5.4,
			xMax: 5.5,
			zMin: -4.5,
			zMax: 5.5,
		},
		{
			key: 1,
			name: 'Wood center table',
			img: 'https://i.imgur.com/yNGxqxr.png',
			model: <Living2 />,
			w: 20.2,
			l: 18,
			rotation: 0,
			isActive: false,
			isShown: false,
			color: {
				Wood: null,
			},
			xMin: -5.4,
			xMax: 5.5,
			zMin: -4.5,
			zMax: 5.5,
		},
		{
			key: 2,
			name: 'Single Couch',
			img: 'https://i.imgur.com/XRrcGLb.png',
			model: <Living3 />,
			w: 30.4,
			l: 41,
			rotation: 0,
			isActive: false,
			isShown: false,
			color: {
				Seat: null,
				Foam: null,
				Frame: null,
			},
			xMin: -5.4,
			xMax: 5.5,
			zMin: -4.5,
			zMax: 5.5,
		},

		{
			key: 3,
			name: 'Corner Sofa',
			img: 'https://i.imgur.com/XEPh9qa.png',
			model: <Living4 />,
			w: 89.6,
			l: 40.3,
			rotation: 0,
			isActive: false,
			isShown: false,
			color: {
				Sofa: null,
				Stitches: null,
				Seat: null,
				Legs: null,
			},
			xMin: -5.4,
			xMax: 5.5,
			zMin: -4.5,
			zMax: 5.5,
		},
		{
			key: 4,
			name: 'Class coffee table',
			img: 'https://i.imgur.com/GxK0tdi.png',
			model: <Living5 />,
			w: 30.3,
			l: 20.4,
			rotation: 0,
			isActive: false,
			isShown: false,
			color: {
				FirstLeg: null,
				SecondLeg: null,
				Glass: null,
			},
			xMin: -5.4,
			xMax: 5.5,
			zMin: -4.5,
			zMax: 5.5,
		},
		{
			key: 5,
			name: 'Small Cabinet',
			img: 'https://i.imgur.com/F6vygUM.png',
			model: <Living6 />,
			w: 28.7,
			l: 20.2,
			rotation: 0,
			isActive: false,
			isShown: false,
			color: {
				Box: null,
				Handle: null,
			},
			xMin: -5.4,
			xMax: 5.5,
			zMin: -4.5,
			zMax: 5.5,
		},

		{
			key: 6,
			name: 'Shelves',
			img: 'https://i.imgur.com/3NTsXPv.png',
			model: <Living7 />,
			w: 39.4,
			l: 60.2,
			rotation: 0,
			isActive: false,
			isShown: false,
			color: {
				Shelves: null,
				Panel: null,
			},
			xMin: -5.4,
			xMax: 5.5,
			zMin: -4.5,
			zMax: 5.5,
		},

		{
			key: 7,
			name: 'Big Shelves',
			img: 'https://i.imgur.com/3rPb2fd.png',
			model: <Living8 />,
			w: 77.3,
			l: 70,
			rotation: 0,
			isActive: false,
			isShown: false,
			color: {
				Shelves: null,
				Panel: null,
			},
			xMin: -5.4,
			xMax: 5.5,
			zMin: -4.5,
			zMax: 5.5,
		},

		{
			key: 8,
			name: 'TV',
			img: 'https://i.imgur.com/EF8KLLD.png',
			model: <Living9 />,
			w: 35.3,
			l: 32,
			rotation: 0,
			isActive: false,
			isShown: false,
			color: {
				TV: null,
				Furniture: null,
			},
			xMin: -5.4,
			xMax: 5.5,
			zMin: -4.5,
			zMax: 5.5,
		},
	]);
	//bathroom models
	const [bathroomFurn, setBathroomFurn] = useState([
		{
			key: 0,
			name: 'Bathub',
			img: 'https://i.imgur.com/yhrYOxx.png',
			model: <Bath1 />,
			w: 31,
			l: 18.5,
			rotation: 0,
			isActive: false,
			isShown: false,
			color: {
				Body: null,
			},
			xMin: -5.4,
			xMax: 5.5,
			zMin: -4.5,
			zMax: 5.5,
		},
		{
			key: 1,
			name: 'Shower Cabin',
			img: 'https://i.imgur.com/EHbleBt.png',
			model: <Bath2 />,
			w: 28,
			l: 56,
			rotation: 0,
			isActive: false,
			isShown: false,
			color: {
				Body: null,
				Glass: null,
				Shower: null,
			},
			xMin: -5.4,
			xMax: 5.5,
			zMin: -4.5,
			zMax: 5.5,
		},
		{
			key: 2,
			name: 'Bathroom Sink',
			img: 'https://i.imgur.com/TGPQNnS.png',
			model: <Bath3 />,
			w: 18,
			l: 34,
			rotation: 0,
			isActive: false,
			isShown: false,
			color: {
				Body: null,
			},
			xMin: -5.4,
			xMax: 5.5,
			zMin: -4.5,
			zMax: 5.5,
		},
		{
			key: 3,
			name: 'Bathroom Mirror',
			img: 'https://i.imgur.com/LDceuN3.png',
			model: <Bath4 />,
			w: 14,
			l: 20,
			rotation: 0,
			isActive: false,
			isShown: false,
			color: {
				Body: null,
			},
			xMin: -5.4,
			xMax: 5.5,
			zMin: -4.5,
			zMax: 5.5,
		},
		{
			key: 4,
			name: 'Bathroom Bucket',
			img: 'https://i.imgur.com/fwfClvx.png',
			model: <Bath5 />,
			w: 31,
			l: 31,
			rotation: 0,
			isActive: false,
			isShown: false,
			color: {
				Body: null,
			},
			xMin: -5.4,
			xMax: 5.5,
			zMin: -4.5,
			zMax: 5.5,
		},
		{
			key: 5,
			name: 'Sink with cabinet',
			img: 'https://i.imgur.com/nGgJOZ7.png',
			model: <Bath6 />,
			w: 30,
			l: 28,
			rotation: 0,
			isActive: false,
			isShown: false,
			color: {
				Drain: null,
				Main: null,
				Sink: null,
				Table: null,
			},
			xMin: -5.4,
			xMax: 5.5,
			zMin: -4.5,
			zMax: 5.5,
		},
		{
			key: 6,
			name: 'Toilet',
			img: 'https://i.imgur.com/UeeEEfZ.png',
			model: <Bath7 />,
			w: 13.5,
			l: 30,
			rotation: 0,
			isActive: false,
			isShown: false,
			color: {
				Body: null,
			},
			xMin: -5.4,
			xMax: 5.5,
			zMin: -4.5,
			zMax: 5.5,
		},
		{
			key: 7,
			name: 'Shower',
			img: 'https://i.imgur.com/HOjimgW.png',
			model: <Bath8 />,
			w: 8,
			l: 30,
			rotation: 0,
			isActive: false,
			isShown: false,
			color: {
				Body: null,
			},
			xMin: -5.4,
			xMax: 5.5,
			zMin: -4.5,
			zMax: 5.5,
		},
		{
			key: 8,
			name: 'Wall Mounted Bathroom Shelves',
			img: 'https://i.imgur.com/GWwJlif.png',
			model: <Bath9 />,
			w: 16,
			l: 16,
			rotation: 0,
			isActive: false,
			isShown: false,
			color: {
				Body: null,
			},
			xMin: -5.4,
			xMax: 5.5,
			zMin: -4.5,
			zMax: 5.5,
		},
	]);
	return (
		<FurnitureContext.Provider
			value={{
				bedroomFurn,
				setBedroom,
				livingroomFurn,
				setLivingroom,
				diningRoomFurn,
				setDiningRoomFurn,
				activeFurn,
				setActiveFurn,
				kitchenFurn,
				setKitchenFurn,
				bathroomFurn,
				setBathroomFurn,
			}}
		>
			{props.children}
		</FurnitureContext.Provider>
	);
};

export const useCustomization = () => {
	const context = useContext(FurnitureContext);
	return context;
};
