import { createContext, useContext, useState } from 'react';

import {
	Bed1,
	Bed2,
	Bed3,
	Bed4,
	Bed5,
	Bed6,
	Bed7,
	Bed8,
	Bed9,
	Living1,
	Living2,
	Living3,
	Living4,
	Living5,
	Living6,
	Living7,
	Living8,
	Living9,
	Kitchen1,
	Kitchen2,
	Kitchen3,
	Kitchen4,
	Kitchen5,
	Kitchen6,
	Kitchen7,
	Kitchen8,
	Kitchen9,
	Dining1,
	Dining2,
	Dining3,
	Dining4,
	Dining5,
	Dining6,
	Dining7,
	Dining8,
	Dining9,
	Bath1,
	Bath2,
	Bath3,
	Bath4,
	Bath5,
	Bath6,
	Bath7,
	Bath8,
	Bath9,
} from './src/assets';

const FurnitureContext = createContext({});

export const FurnitureProvider = (props) => {
	const [activeFurn, setActiveFurn] = useState([]);

	//bedroom models
	const [kitchenFurn, setKitchenFurn] = useState([
		{
			key: 0,
			name: 'Top Freezer Refrigerator',
			img: 'https://firebasestorage.googleapis.com/v0/b/icodes-ctc-db1.appspot.com/o/interactive%2Fkitchen%2Fkitchen1.png?alt=media&token=1d45249f-5efc-45f1-ad99-b416eac2e48d',
			model: <Kitchen1 />,
			w: 30,
			l: 30,
			rotation: 0,
			isActive: false,
			isShown: false,
			color: {
				Body: null,
			},
			xMin: -5.4,
			xMax: 5.5,
			zMin: -4.5,
			zMax: 5.5,
		},
		{
			key: 1,
			name: 'Double Stove',
			img: 'https://firebasestorage.googleapis.com/v0/b/icodes-ctc-db1.appspot.com/o/interactive%2Fkitchen%2Fkitchen2.png?alt=media&token=173eb85f-81af-4f10-ad38-5b38ec65a752',
			model: <Kitchen2 />,
			w: 45.2,
			l: 36.1,
			rotation: 0,
			isActive: false,
			isShown: false,
			color: {
				Back: null,
				Window: null,
				Box: null,
				Stove: null,
			},
			xMin: -5.4,
			xMax: 5.5,
			zMin: -4.5,
			zMax: 5.5,
		},
		{
			key: 2,
			name: 'Wall-Mounted Kitchen Storage',
			img: 'https://firebasestorage.googleapis.com/v0/b/icodes-ctc-db1.appspot.com/o/interactive%2Fkitchen%2Fkitchen3.png?alt=media&token=598dd514-b2e5-411b-bfea-064355db4eca',
			model: <Kitchen3 />,
			w: 30.3,
			l: 21.1,
			rotation: 0,
			isActive: false,
			isShown: false,
			color: {
				Shelves: null,
				Box: null,
			},
			xMin: -5.4,
			xMax: 5.5,
			zMin: -4.5,
			zMax: 5.5,
		},

		{
			key: 3,
			name: 'Tall Kitchen Table',
			img: 'https://firebasestorage.googleapis.com/v0/b/icodes-ctc-db1.appspot.com/o/interactive%2Fkitchen%2Fkitchen4.png?alt=media&token=f7808ab8-1002-4010-9896-34a645aa496b',
			model: <Kitchen4 />,
			w: 19.4,
			l: 40.3,
			rotation: 0,
			isActive: false,
			isShown: false,
			color: {
				Color: null,
			},
			xMin: -5.4,
			xMax: 5.5,
			zMin: -4.5,
			zMax: 5.5,
		},

		{
			key: 4,
			name: 'Corner Kitchen Sink with Stove',
			img: 'https://firebasestorage.googleapis.com/v0/b/icodes-ctc-db1.appspot.com/o/interactive%2Fkitchen%2Fkitchen5.png?alt=media&token=230867ed-835b-4180-9726-854871b0e591',
			model: <Kitchen5 />,
			w: 90.3,
			l: 68.5,
			rotation: 0,
			isActive: false,
			isShown: false,
			color: {
				Color: null,
				Stove: null,
				Sink: null,
			},
			xMin: -5.4,
			xMax: 5.5,
			zMin: -4.5,
			zMax: 5.5,
		},
		{
			key: 5,
			name: 'Small Kitchen Cabinet',
			img: 'https://firebasestorage.googleapis.com/v0/b/icodes-ctc-db1.appspot.com/o/interactive%2Fkitchen%2Fkitchen6.png?alt=media&token=83a10837-0448-4409-b136-b9121f0c1bdf',
			model: <Kitchen6 />,
			w: 17.6,
			l: 30,
			rotation: 0,
			isActive: false,
			isShown: false,
			color: {
				Color: null,
				Handle: null,
			},
			xMin: -5.4,
			xMax: 5.5,
			zMin: -4.5,
			zMax: 5.5,
		},
		{
			key: 6,
			name: 'Long Kitchen Cabinet',
			img: 'https://firebasestorage.googleapis.com/v0/b/icodes-ctc-db1.appspot.com/o/interactive%2Fkitchen%2Fkitchen7.png?alt=media&token=155a105b-5801-4742-8487-d5c41eee7b6b',
			model: <Kitchen7 />,
			w: 82.1,
			l: 29,
			rotation: 0,
			isActive: false,
			isShown: false,
			color: {
				Color: null,
			},
			xMin: -5.4,
			xMax: 5.5,
			zMin: -4.5,
			zMax: 5.5,
		},
		{
			key: 7,
			name: 'Small Kitchen Sink',
			img: 'https://firebasestorage.googleapis.com/v0/b/icodes-ctc-db1.appspot.com/o/interactive%2Fkitchen%2Fkitchen8.png?alt=media&token=bb47a7e6-083b-4bc0-a36b-d132551cd78c',
			model: <Kitchen8 />,
			w: 39.2,
			l: 32.6,
			rotation: 0,
			isActive: false,
			isShown: false,
			color: {
				Color: null,
				Handle: null,
				Sink: null,
			},
			xMin: -5.4,
			xMax: 5.5,
			zMin: -4.5,
			zMax: 5.5,
		},
		{
			key: 8,
			name: 'Small oven with stove',
			img: 'https://firebasestorage.googleapis.com/v0/b/icodes-ctc-db1.appspot.com/o/interactive%2Fkitchen%2Fkitchen9.png?alt=media&token=53300698-1475-4ba9-bb14-03797e893f6b',
			model: <Kitchen9 />,
			w: 30.4,
			l: 27.2,
			rotation: 0,
			isActive: false,
			isShown: false,
			color: {
				Color: null,
			},
			xMin: -5.4,
			xMax: 5.5,
			zMin: -4.5,
			zMax: 5.5,
		},
	]);
	//diningroom models
	const [diningRoomFurn, setDiningRoomFurn] = useState([
		{
			key: 0,
			name: 'Breakfast Bar',
			img: 'https://firebasestorage.googleapis.com/v0/b/icodes-ctc-db1.appspot.com/o/interactive%2Fdining%2Fdining1.png?alt=media&token=95df2c39-4531-446a-8a91-ef5b8f2102f0',
			model: <Dining1 />,
			w: 58.2,
			l: 43.1,
			rotation: 0,
			isActive: false,
			isShown: false,
			color: {
				Body: null,
				Chair: null,
				Legs: null,
			},
			xMin: -5.4,
			xMax: 5.5,
			zMin: -4.5,
			zMax: 5.5,
		},

		{
			key: 1,
			name: 'Small Dining Table Set',
			img: 'https://firebasestorage.googleapis.com/v0/b/icodes-ctc-db1.appspot.com/o/interactive%2Fdining%2Fdining2.png?alt=media&token=f351ae57-b391-4617-ae3a-a9bcc2188f68',
			model: <Dining2 />,
			w: 35.5,
			l: 31.4,
			rotation: 0,
			isActive: false,
			isShown: false,
			color: {
				Table: null,
				Chair: null,
			},
			xMin: -5.4,
			xMax: 5.5,
			zMin: -4.5,
			zMax: 5.5,
		},
		{
			key: 2,
			name: 'Big Dining Table Set',
			img: 'https://firebasestorage.googleapis.com/v0/b/icodes-ctc-db1.appspot.com/o/interactive%2Fdining%2Fdining3.png?alt=media&token=5d0afb40-0224-4aef-8e91-17734e054017',
			model: <Dining3 />,
			w: 88.2,
			l: 31,
			rotation: 0,
			isActive: false,
			isShown: false,
			color: {
				Table: null,
				Chair: null,
			},
			xMin: -5.4,
			xMax: 5.5,
			zMin: -4.5,
			zMax: 5.5,
		},

		{
			key: 3,
			name: 'Dining Cabinet',
			img: 'https://firebasestorage.googleapis.com/v0/b/icodes-ctc-db1.appspot.com/o/interactive%2Fdining%2Fdining4.png?alt=media&token=5448d9d7-dc9c-47ba-8728-ee0cfbd23944',
			model: <Dining4 />,
			w: 45,
			l: 33,
			rotation: 0,
			isActive: false,
			isShown: false,
			color: {
				Body: null,
			},
			xMin: -5.4,
			xMax: 5.5,
			zMin: -4.5,
			zMax: 5.5,
		},

		{
			key: 4,
			name: 'Single Dining Chair',
			img: 'https://firebasestorage.googleapis.com/v0/b/icodes-ctc-db1.appspot.com/o/interactive%2Fdining%2Fdining5.png?alt=media&token=a623e8b1-f503-4792-9044-507b14bcad21',
			model: <Dining5 />,
			w: 15.3,
			l: 30,
			rotation: 0,
			isActive: false,
			isShown: false,
			color: {
				Body: null,
			},
			xMin: -5.4,
			xMax: 5.5,
			zMin: -4.5,
			zMax: 5.5,
		},
		{
			key: 5,
			name: 'Round Table',
			img: 'https://firebasestorage.googleapis.com/v0/b/icodes-ctc-db1.appspot.com/o/interactive%2Fdining%2Fdining6.png?alt=media&token=4b5c7a08-d6bf-4ef5-9cf5-92956ac47088',
			model: <Dining6 />,
			w: 28,
			l: 24,
			rotation: 0,
			isActive: false,
			isShown: false,
			color: {
				Body: null,
			},
			xMin: -5.4,
			xMax: 5.5,
			zMin: -4.5,
			zMax: 5.5,
		},
		{
			key: 6,
			name: 'Marble Table',
			img: 'https://firebasestorage.googleapis.com/v0/b/icodes-ctc-db1.appspot.com/o/interactive%2Fdining%2Fdining7.png?alt=media&token=614d6336-8b18-42e5-9a8a-538622637e84',
			model: <Dining7 />,
			w: 32,
			l: 28.1,
			rotation: 0,
			isActive: false,
			isShown: false,
			color: {
				Table: null,
				Stand: null,
			},
			xMin: -5.4,
			xMax: 5.5,
			zMin: -4.5,
			zMax: 5.5,
		},

		{
			key: 7,
			name: 'Single Dining Chair',
			img: 'https://firebasestorage.googleapis.com/v0/b/icodes-ctc-db1.appspot.com/o/interactive%2Fdining%2Fdining8.png?alt=media&token=0f80380c-b706-4622-bfd0-0193784a0f3a',
			model: <Dining8 />,
			w: 15,
			l: 30.3,
			rotation: 0,
			isActive: false,
			isShown: false,
			color: {
				Seat: null,
				Stand: null,
			},
			xMin: -5.4,
			xMax: 5.5,
			zMin: -4.5,
			zMax: 5.5,
		},
		{
			key: 8,
			name: 'Hutch',
			img: 'https://firebasestorage.googleapis.com/v0/b/icodes-ctc-db1.appspot.com/o/interactive%2Fdining%2Fdining9.png?alt=media&token=3e95ec8a-9646-4b38-8184-dbc4e0bdf27a',
			model: <Dining9 />,
			w: 26.5,
			l: 48.1,
			rotation: 0,
			isActive: false,
			isShown: false,
			color: {
				Body: null,
			},
			xMin: -5.4,
			xMax: 5.5,
			zMin: -4.5,
			zMax: 5.5,
		},
	]);
	//bedroom models
	const [bedroomFurn, setBedroom] = useState([
		{
			key: 0,
			name: 'Wooden Bed',
			img: 'https://firebasestorage.googleapis.com/v0/b/icodes-ctc-db1.appspot.com/o/interactive%2Fbedroom%2Fbed1.png?alt=media&token=d20e6284-2de6-4c72-b168-2ba8259d8330',
			model: <Bed1 />,
			w: 60,
			l: 80,
			rotation: 0,
			isActive: false,
			isShown: false,
			color: {
				Mattress: null,
				Pillows: null,
				Sheet: null,
				Board: null,
			},
			xMin: -5.4,
			xMax: 5.5,
			zMin: 5.5,
			zMax: 5.5,
		},
		{
			key: 1,
			name: 'Bed with Side Table',
			img: 'https://firebasestorage.googleapis.com/v0/b/icodes-ctc-db1.appspot.com/o/interactive%2Fbedroom%2Fbed2.png?alt=media&token=548b2838-faf4-483e-91d1-816a9aa6bf61',
			model: <Bed2 />,
			w: 80,
			l: 80,
			rotation: 0,
			isActive: false,
			isShown: false,
			color: {
				Mattress: null,
				Board: null,
			},
			xMin: -5.4,
			xMax: 5.5,
			zMin: 5.5,
			zMax: 5.5,
		},
		{
			key: 2,
			name: 'Bed with Steel Board',
			img: 'https://firebasestorage.googleapis.com/v0/b/icodes-ctc-db1.appspot.com/o/interactive%2Fbedroom%2Fbed3.png?alt=media&token=7acbbfce-0d0a-44ad-9429-204dbc509af7',
			model: <Bed3 />,
			w: 39,
			l: 80,
			rotation: 0,
			isActive: false,
			isShown: false,
			color: {
				Mattress: null,
				Pillows: null,
				Sheet: null,
				Board: null,
			},
			xMin: -5.4,
			xMax: 5.5,
			zMin: -4.5,
			zMax: 5.5,
		},
		{
			key: 3,
			name: 'Bed with Head Board',
			img: 'https://firebasestorage.googleapis.com/v0/b/icodes-ctc-db1.appspot.com/o/interactive%2Fbedroom%2Fbed4.png?alt=media&token=f7c375e7-20fa-47e6-aaf9-8b51c8bda9e0',
			model: <Bed4 />,
			w: 60,
			l: 80,
			rotation: 0,
			isActive: false,
			isShown: false,
			color: {
				Mattress: null,
				Pillows: null,
				Sheet: null,
				Board: null,
			},
			xMin: -5.4,
			xMax: 5.5,
			zMin: -0.3,
			zMax: 0.2,
		},

		{
			key: 4,
			name: 'Long Bed',
			img: 'https://firebasestorage.googleapis.com/v0/b/icodes-ctc-db1.appspot.com/o/interactive%2Fbedroom%2Fbed5.png?alt=media&token=be042d71-ad71-48c4-b887-9af1fd3fa68c',
			model: <Bed5 />,
			w: 40,
			l: 80,

			rotation: 0,
			isActive: false,
			isShown: false,
			color: {
				Sheet: null,
				Board: null,
			},
			xMin: -5.4,
			xMax: 5.5,
			zMin: -4.5,
			zMax: 5.5,
		},
		{
			key: 5,
			name: 'Double Decker Bed',
			img: 'https://firebasestorage.googleapis.com/v0/b/icodes-ctc-db1.appspot.com/o/interactive%2Fbedroom%2Fbed6.png?alt=media&token=81debdc6-2a15-4c25-bcb0-383010ee7fbe',
			model: <Bed6 />,
			w: 55,
			l: 80,

			rotation: 0,
			isActive: false,
			isShown: false,
			color: {
				Color: null,
			},
			xMin: -5.4,
			xMax: 5.5,
			zMin: -4.5,
			zMax: 5.5,
		},
		{
			key: 6,
			name: 'Bed with Two Side Table',
			img: 'https://firebasestorage.googleapis.com/v0/b/icodes-ctc-db1.appspot.com/o/interactive%2Fbedroom%2Fbed6.png?alt=media&token=81debdc6-2a15-4c25-bcb0-383010ee7fbe',
			model: <Bed7 />,
			w: 52,
			l: 80,

			rotation: 0,
			isActive: false,
			isShown: false,
			color: {
				Mattress: null,
				Body: null,
				Pillow: null,
			},
			xMin: -5.4,
			xMax: 5.5,
			zMin: -4.5,
			zMax: 5.5,
		},
		{
			key: 7,
			name: 'Luxury Bed',
			img: 'https://firebasestorage.googleapis.com/v0/b/icodes-ctc-db1.appspot.com/o/interactive%2Fbedroom%2Fbed8.png?alt=media&token=1f125ca2-72ae-46ed-bd3c-3034e79db2b1',
			model: <Bed8 />,
			w: 60,
			l: 80,

			rotation: 0,
			isActive: false,
			isShown: false,
			color: {
				Blanket: null,
				Body: null,
				Mattress: null,
			},
			xMin: -5.4,
			xMax: 5.5,
			zMin: -4.5,
			zMax: 5.5,
		},
		{
			key: 8,
			name: 'Round Bed',
			img: 'https://firebasestorage.googleapis.com/v0/b/icodes-ctc-db1.appspot.com/o/interactive%2Fbedroom%2Fbed9.png?alt=media&token=46977a85-444a-41e7-9c3e-9397ff922f09',
			model: <Bed9 />,
			w: 46,
			l: 80,

			rotation: 0,
			isActive: false,
			isShown: false,
			color: {
				Blanket: null,
				Mattress: null,
				Sheet: null,
				Wood: null,
				Pillow: null,
			},
			xMin: -5.4,
			xMax: 5.5,
			zMin: -4.5,
			zMax: 5.5,
		},
	]);
	//livingroom models
	const [livingroomFurn, setLivingroom] = useState([
		{
			key: 0,
			name: 'Double seat Couch',
			img: 'https://firebasestorage.googleapis.com/v0/b/icodes-ctc-db1.appspot.com/o/interactive%2Fliving%2Fliving1.png?alt=media&token=470c2780-354c-4c54-bc90-6a46cb8c0be9',
			model: <Living1 />,
			w: 80.2,
			l: 30.1,
			rotation: 0,
			isActive: false,
			isShown: false,
			color: {
				Sofa: null,
			},
			xMin: -5.4,
			xMax: 5.5,
			zMin: -4.5,
			zMax: 5.5,
		},
		{
			key: 1,
			name: 'Wood center table',
			img: 'https://firebasestorage.googleapis.com/v0/b/icodes-ctc-db1.appspot.com/o/interactive%2Fliving%2Fliving2.png?alt=media&token=6d0a71b7-c4e3-4e02-a417-10ab1a31542d',
			model: <Living2 />,
			w: 20.2,
			l: 18,
			rotation: 0,
			isActive: false,
			isShown: false,
			color: {
				Wood: null,
			},
			xMin: -5.4,
			xMax: 5.5,
			zMin: -4.5,
			zMax: 5.5,
		},
		{
			key: 2,
			name: 'Single Couch',
			img: 'https://firebasestorage.googleapis.com/v0/b/icodes-ctc-db1.appspot.com/o/interactive%2Fliving%2Fliving3.png?alt=media&token=345b94a2-fbfc-4208-95a2-daaff7bb7be2',
			model: <Living3 />,
			w: 30.4,
			l: 41,
			rotation: 0,
			isActive: false,
			isShown: false,
			color: {
				Seat: null,
				Foam: null,
				Frame: null,
			},
			xMin: -5.4,
			xMax: 5.5,
			zMin: -4.5,
			zMax: 5.5,
		},

		{
			key: 3,
			name: 'Corner Sofa',
			img: 'https://firebasestorage.googleapis.com/v0/b/icodes-ctc-db1.appspot.com/o/interactive%2Fliving%2Fliving4.png?alt=media&token=740ef6ca-9815-4c94-939f-0b6b009e844b',
			model: <Living4 />,
			w: 89.6,
			l: 40.3,
			rotation: 0,
			isActive: false,
			isShown: false,
			color: {
				Sofa: null,
				Stitches: null,
				Seat: null,
				Legs: null,
			},
			xMin: -5.4,
			xMax: 5.5,
			zMin: -4.5,
			zMax: 5.5,
		},
		{
			key: 4,
			name: 'Class coffee table',
			img: 'https://firebasestorage.googleapis.com/v0/b/icodes-ctc-db1.appspot.com/o/interactive%2Fliving%2Fliving5.png?alt=media&token=d159ea47-90cf-4ed5-adf7-372523020fc5',
			model: <Living5 />,
			w: 30.3,
			l: 20.4,
			rotation: 0,
			isActive: false,
			isShown: false,
			color: {
				FirstLeg: null,
				SecondLeg: null,
				Glass: null,
			},
			xMin: -5.4,
			xMax: 5.5,
			zMin: -4.5,
			zMax: 5.5,
		},
		{
			key: 5,
			name: 'Small Cabinet',
			img: 'https://firebasestorage.googleapis.com/v0/b/icodes-ctc-db1.appspot.com/o/interactive%2Fliving%2Fliving6.png?alt=media&token=2e194ba1-91a4-42e0-9308-077d5bc558db',
			model: <Living6 />,
			w: 28.7,
			l: 20.2,
			rotation: 0,
			isActive: false,
			isShown: false,
			color: {
				Box: null,
				Handle: null,
			},
			xMin: -5.4,
			xMax: 5.5,
			zMin: -4.5,
			zMax: 5.5,
		},

		{
			key: 6,
			name: 'Shelves',
			img: 'https://firebasestorage.googleapis.com/v0/b/icodes-ctc-db1.appspot.com/o/interactive%2Fliving%2Fliving7.png?alt=media&token=5191f784-9e49-4a2c-98b0-ae515eba260b',
			model: <Living7 />,
			w: 39.4,
			l: 60.2,
			rotation: 0,
			isActive: false,
			isShown: false,
			color: {
				Shelves: null,
				Panel: null,
			},
			xMin: -5.4,
			xMax: 5.5,
			zMin: -4.5,
			zMax: 5.5,
		},

		{
			key: 7,
			name: 'Big Shelves',
			img: 'https://firebasestorage.googleapis.com/v0/b/icodes-ctc-db1.appspot.com/o/interactive%2Fliving%2Fliving8.png?alt=media&token=f661d342-703e-4f7d-935a-15a65259650e',
			model: <Living8 />,
			w: 77.3,
			l: 70,
			rotation: 0,
			isActive: false,
			isShown: false,
			color: {
				Shelves: null,
				Panel: null,
			},
			xMin: -5.4,
			xMax: 5.5,
			zMin: -4.5,
			zMax: 5.5,
		},

		{
			key: 8,
			name: 'TV',
			img: 'https://firebasestorage.googleapis.com/v0/b/icodes-ctc-db1.appspot.com/o/interactive%2Fliving%2Fliving9.png?alt=media&token=9568503d-817d-49c3-9f42-dcc159edb938',
			model: <Living9 />,
			w: 35.3,
			l: 32,
			rotation: 0,
			isActive: false,
			isShown: false,
			color: {
				TV: null,
				Furniture: null,
			},
			xMin: -5.4,
			xMax: 5.5,
			zMin: -4.5,
			zMax: 5.5,
		},
	]);
	//bathroom models
	const [bathroomFurn, setBathroomFurn] = useState([
		{
			key: 0,
			name: 'Bathub',
			img: 'https://firebasestorage.googleapis.com/v0/b/icodes-ctc-db1.appspot.com/o/interactive%2Fbathroom%2Fbath1.png?alt=media&token=e435e1bc-8df3-4841-8820-0b76f4186e00',
			model: <Bath1 />,
			w: 31,
			l: 18.5,
			rotation: 0,
			isActive: false,
			isShown: false,
			color: {
				Body: null,
			},
			xMin: -5.4,
			xMax: 5.5,
			zMin: -4.5,
			zMax: 5.5,
		},
		{
			key: 1,
			name: 'Shower Cabin',
			img: 'https://firebasestorage.googleapis.com/v0/b/icodes-ctc-db1.appspot.com/o/interactive%2Fbathroom%2Fbath2.png?alt=media&token=7bff2961-8e7c-42b1-aa65-669444710418',
			model: <Bath2 />,
			w: 28,
			l: 56,
			rotation: 0,
			isActive: false,
			isShown: false,
			color: {
				Body: null,
				Glass: null,
				Shower: null,
			},
			xMin: -5.4,
			xMax: 5.5,
			zMin: -4.5,
			zMax: 5.5,
		},
		{
			key: 2,
			name: 'Bathroom Sink',
			img: 'https://firebasestorage.googleapis.com/v0/b/icodes-ctc-db1.appspot.com/o/interactive%2Fbathroom%2Fbath3.png?alt=media&token=45be97f7-04df-43f7-9012-6a92976bb91d',
			model: <Bath3 />,
			w: 18,
			l: 34,
			rotation: 0,
			isActive: false,
			isShown: false,
			color: {
				Body: null,
			},
			xMin: -5.4,
			xMax: 5.5,
			zMin: -4.5,
			zMax: 5.5,
		},
		{
			key: 3,
			name: 'Bathroom Mirror',
			img: 'https://firebasestorage.googleapis.com/v0/b/icodes-ctc-db1.appspot.com/o/interactive%2Fbathroom%2Fbath3.png?alt=media&token=45be97f7-04df-43f7-9012-6a92976bb91d',
			model: <Bath4 />,
			w: 14,
			l: 20,
			rotation: 0,
			isActive: false,
			isShown: false,
			color: {
				Body: null,
			},
			xMin: -5.4,
			xMax: 5.5,
			zMin: -4.5,
			zMax: 5.5,
		},
		{
			key: 4,
			name: 'Bathroom Bucket',
			img: 'https://firebasestorage.googleapis.com/v0/b/icodes-ctc-db1.appspot.com/o/interactive%2Fbathroom%2Fbath5.png?alt=media&token=10e4abb5-069e-495d-aa84-da8bfdd1ef3e',
			model: <Bath5 />,
			w: 31,
			l: 31,
			rotation: 0,
			isActive: false,
			isShown: false,
			color: {
				Body: null,
			},
			xMin: -5.4,
			xMax: 5.5,
			zMin: -4.5,
			zMax: 5.5,
		},
		{
			key: 5,
			name: 'Sink with cabinet',
			img: 'https://firebasestorage.googleapis.com/v0/b/icodes-ctc-db1.appspot.com/o/interactive%2Fbathroom%2Fbath6.png?alt=media&token=f67c851e-de03-4285-bba4-dd24a25f34d9',
			model: <Bath6 />,
			w: 30,
			l: 28,
			rotation: 0,
			isActive: false,
			isShown: false,
			color: {
				Drain: null,
				Main: null,
				Sink: null,
				Table: null,
			},
			xMin: -5.4,
			xMax: 5.5,
			zMin: -4.5,
			zMax: 5.5,
		},
		{
			key: 6,
			name: 'Toilet',
			img: 'https://firebasestorage.googleapis.com/v0/b/icodes-ctc-db1.appspot.com/o/interactive%2Fbathroom%2Fbath7.png?alt=media&token=f06d47e7-8854-4225-ab85-f63622bb8404',
			model: <Bath7 />,
			w: 13.5,
			l: 30,
			rotation: 0,
			isActive: false,
			isShown: false,
			color: {
				Body: null,
			},
			xMin: -5.4,
			xMax: 5.5,
			zMin: -4.5,
			zMax: 5.5,
		},
		{
			key: 7,
			name: 'Shower',
			img: 'https://firebasestorage.googleapis.com/v0/b/icodes-ctc-db1.appspot.com/o/interactive%2Fbathroom%2Fbath8.png?alt=media&token=d622bd93-5d02-4562-9407-e20d7fa6567c',
			model: <Bath8 />,
			w: 8,
			l: 30,
			rotation: 0,
			isActive: false,
			isShown: false,
			color: {
				Body: null,
			},
			xMin: -5.4,
			xMax: 5.5,
			zMin: -4.5,
			zMax: 5.5,
		},
		{
			key: 8,
			name: 'Wall Mounted Bathroom Shelves',
			img: 'https://firebasestorage.googleapis.com/v0/b/icodes-ctc-db1.appspot.com/o/interactive%2Fbathroom%2Fbath8.png?alt=media&token=d622bd93-5d02-4562-9407-e20d7fa6567c',
			model: <Bath9 />,
			w: 16,
			l: 16,
			rotation: 0,
			isActive: false,
			isShown: false,
			color: {
				Body: null,
			},
			xMin: -5.4,
			xMax: 5.5,
			zMin: -4.5,
			zMax: 5.5,
		},
	]);
	return (
		<FurnitureContext.Provider
			value={{
				bedroomFurn,
				setBedroom,
				livingroomFurn,
				setLivingroom,
				diningRoomFurn,
				setDiningRoomFurn,
				activeFurn,
				setActiveFurn,
				kitchenFurn,
				setKitchenFurn,
				bathroomFurn,
				setBathroomFurn,
			}}
		>
			{props.children}
		</FurnitureContext.Provider>
	);
};

export const useCustomization = () => {
	const context = useContext(FurnitureContext);
	return context;
};
