/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 bed1.glb
*/

import React, { forwardRef } from 'react';
import { useGLTF } from '@react-three/drei';

const Bed1 = forwardRef(({ events, props, action, rotate, color }, ref) => {
	const { nodes, materials } = useGLTF('/bed1.glb');

	return (
		<group
			dispose={null}
			{...props}
			{...events}
			ref={ref}
			onClick={action}
			rotation-y={rotate}
		>
			<mesh
				geometry={nodes.Flat_Sheet.geometry}
				material={materials.Blanket}
				material-color={color.Sheet}
			/>
			<mesh
				geometry={nodes.HeadFoot_Board.geometry}
				material={materials.Brown_Wood}
				material-color={color.Board}
			/>
			<mesh
				geometry={nodes.Mattress.geometry}
				material={materials.Matress}
				material-color={color.Mattress}
			/>
			<mesh
				geometry={nodes.Pillows.geometry}
				material={materials.Pillow}
				material-color={color.Pillows}
			/>
			<mesh
				geometry={nodes.Rails.geometry}
				material={materials.Rails}
			/>
		</group>
	);
});

useGLTF.preload('/bed1.glb');

export default Bed1;
