/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 bed2.glb
*/

import React, { forwardRef } from 'react';
import { useGLTF } from '@react-three/drei';

const Bed2 = forwardRef(({ events, props, action, rotate, color }, ref) => {
	const { nodes, materials } = useGLTF('/bed2.glb');
	return (
		<group
			dispose={null}
			{...props}
			{...events}
			ref={ref}
			onClick={action}
			rotation-y={rotate}
		>
			<group rotation={[-Math.PI / 2, 0, 0]}>
				<group position={[-130.96, -89.36, 4.81]}>
					<mesh
						geometry={nodes.Flat_Sheet.geometry}
						material={materials.fabric}
					/>
					<mesh
						geometry={nodes.HeadFoot_Board.geometry}
						material={materials.Wood_polish}
						material-color={color.Board}
					/>
					<mesh
						geometry={nodes.Mattress.geometry}
						material={materials.fabric}
						material-color={color.Mattress}
					/>
					<mesh
						geometry={nodes.Object_3.geometry}
						material={materials.fabric}
					/>
					<mesh
						geometry={nodes.Object_6.geometry}
						material={materials.fabric}
					/>
					<mesh
						geometry={nodes.Object_8.geometry}
						material={materials.Wood_polish_black}
					/>
				</group>
			</group>
		</group>
	);
});

useGLTF.preload('/bed2.glb');

export default Bed2;
