/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 bed3.glb
*/
import React, { forwardRef } from 'react';
import { useGLTF } from '@react-three/drei';

const Bed3 = forwardRef(({ events, props, action, rotate, color }, ref) => {
	const { nodes, materials } = useGLTF('/bed3.glb');
	return (
		<group
			dispose={null}
			{...props}
			{...events}
			ref={ref}
			onClick={action}
			rotation-y={rotate}
		>
			<group rotation={[-Math.PI / 2, 0, 0]}>
				<mesh
					geometry={nodes['������������_0'].geometry}
					material={materials['tkan_matras.001']}
					scale={[3.46, 2.06, 0.09]}
					material-color={color.Mattress ? color.Mattress : null}
				/>
				<mesh
					geometry={nodes['������������_0001'].geometry}
					material={materials['tkan_odeyalo.001']}
					position={[1.12, 0.04, 0.46]}
					material-color={color.Sheet ? color.Sheet : null}
				/>
				<mesh
					geometry={nodes['��������������_0'].geometry}
					material={materials['mramor_krovat.001']}
					material-color={color.Board ? color.Board : null}
				/>
				<mesh
					geometry={nodes['��������������001_0'].geometry}
					material={materials['tkan_podushki.001']}
					position={[-2.78, -1, 0.97]}
					scale={[0.73, 1.08, 0.74]}
					material-color={color.Pillows ? color.Pillows : null}
				/>
				<mesh
					geometry={nodes['������������������_0'].geometry}
					material={materials['tkan_pokryvalo.001']}
					position={[1.51, 0.04, 0.52]}
					scale={[0.96, 3.61, 2.3]}
				/>
			</group>
		</group>
	);
});

useGLTF.preload('/bed3.glb');

export default Bed3;
