/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 bed4.glb
*/

import React, { forwardRef } from 'react';
import { useGLTF } from '@react-three/drei';

const Bed4 = forwardRef(({ events, props, action, rotate, color }, ref) => {
	const { nodes, materials } = useGLTF('/bed4.glb');
	return (
		<group
			dispose={null}
			{...props}
			{...events}
			ref={ref}
			onClick={action}
			rotation-y={rotate}
		>
			<group rotation={[-Math.PI / 2, 0, 0]}>
				<group position={[0, 7.09, 1.32]}>
					<mesh
						geometry={nodes['������������_0001'].geometry}
						material={materials.leather}
					/>
					<mesh
						geometry={nodes['������������_1'].geometry}
						material={materials.wood}
					/>
				</group>
				<mesh
					geometry={nodes.Cube_0.geometry}
					material={materials.wood}
				/>
				<mesh
					geometry={nodes['����������_0'].geometry}
					material={materials.wood}
					position={[2.17, 6.11, 0.97]}
					material-color={color.Board ? color.Board : null}
				/>
				<mesh
					geometry={nodes['������������_0'].geometry}
					material={materials.tkan_odeyala}
					position={[0, -1.51, 2.54]}
					material-color={color.Sheets ? color.Sheets : null}
				/>
				<mesh
					geometry={nodes['������������_0002'].geometry}
					material={materials.tkan_odeyala}
					position={[0, 0, 0.62]}
					material-color={color.Mattress ? color.Mattress : null}
				/>
				<mesh
					geometry={nodes['��������������_0'].geometry}
					material={materials.tkan_podushki}
					position={[1.61, 3.81, 2.2]}
					rotation={[0.4, 0, 0]}
					scale={[1.5, 1.02, 1.32]}
					material-color={color.Pillows ? color.Pillows : null}
				/>
				<mesh
					geometry={nodes['��������������001_0'].geometry}
					material={materials.tkan_podushki}
					position={[-1.77, 3.81, 2.2]}
					rotation={[0.4, 0, 0]}
					scale={[1.5, 1.02, 1.32]}
					material-color={color.Pillows ? color.Pillows : null}
				/>
				<mesh
					geometry={nodes['��������������002_0'].geometry}
					material={materials.tkan_podushki}
					position={[2.03, 5.39, 1.81]}
					rotation={[-0.01, 0, 0]}
					scale={[1.87, 1.3, 1.46]}
					material-color={color.Pillows ? color.Pillows : null}
				/>
				<mesh
					geometry={nodes['��������������003_0'].geometry}
					material={materials.tkan_podushki}
					position={[-2.19, 5.39, 1.81]}
					rotation={[-0.01, 0, 0]}
					scale={[1.87, 1.3, 1.46]}
					material-color={color.Pillows ? color.Pillows : null}
				/>
			</group>
		</group>
	);
});

useGLTF.preload('/bed4.glb');

export default Bed4;
