/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 bed5.glb
*/

import React, { useRef, forwardRef } from 'react';
import { useGLTF } from '@react-three/drei';

const Bed5 = forwardRef(({ events, props, action, rotate, color }, ref) => {
	const { nodes, materials } = useGLTF('/bed5.glb');
	return (
		<group
			dispose={null}
			{...props}
			{...events}
			ref={ref}
			onClick={action}
			rotation-y={rotate}
		>
			<group scale={0.01}>
				<group
					position={[7.85, 63.74, 48.11]}
					rotation={[-2.09, 0, 0]}
					scale={[32.58, 21.49, 21.49]}
				>
					<mesh
						geometry={nodes.Plane001_Material_0.geometry}
						material={materials['Material.001']}
						material-color={color.Board ? color.Board : null}
					/>
					<mesh
						geometry={nodes.Plane001_Material_0001.geometry}
						material={materials['Material.001']}
						material-color={color.Sheets ? color.Sheets : null}
					/>
				</group>
			</group>
		</group>
	);
});

useGLTF.preload('/bed5.glb');

export default Bed5;
