/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.12 bed6.glb
*/

import React, { useRef, forwardRef } from 'react';
import { useGLTF } from '@react-three/drei';

const Bed6 = forwardRef(({ events, props, action, rotate, color }, ref) => {
  const { nodes, materials } = useGLTF('/bed6.glb')
  return (
    <group
      dispose={null}
      {...props}
      {...events}
      ref={ref}
      onClick={action}
      rotation-y={rotate}
    >
      <group scale={0.01}>
        <mesh geometry={nodes.Mesh32_Bage_Ceramic10_0.geometry} material={materials.Bage_Ceramic10} material-color={color.Color ? color.Color : null}/>
        <mesh geometry={nodes.Mesh33_Bage_Ceramic10_0.geometry} material={materials.Bage_Ceramic10} material-color={color.Color ? color.Color : null}/>
        <mesh geometry={nodes.Mesh34_Bage_Ceramic10_0.geometry} material={materials.Bage_Ceramic10} material-color={color.Color ? color.Color : null}/>
        <mesh geometry={nodes.Mesh35_Bage_Ceramic10_0.geometry} material={materials.Bage_Ceramic10} material-color={color.Color ? color.Color : null}/>
        <mesh geometry={nodes.Mesh36_Bed_Children_6_0.geometry} material={materials.Bed_Children_6} material-color={color.Color ? color.Color : null}/>
        <mesh geometry={nodes.Mesh37_Bed_Children_6_0.geometry} material={materials.Bed_Children_6} material-color={color.Color ? color.Color : null}/>
        <mesh geometry={nodes.Mesh38_Bed_Children_6_0.geometry} material={materials.Bed_Children_6} material-color={color.Color ? color.Color : null}/>
        <mesh geometry={nodes.Mesh39_Bed_Children_6_0.geometry} material={materials.Bed_Children_6} material-color={color.Color ? color.Color : null}/>
        <mesh geometry={nodes.Mesh40_Bed_Children_6_0.geometry} material={materials.Bed_Children_6} material-color={color.Color ? color.Color : null}/>
        <mesh geometry={nodes.Mesh41_Bed_Children_6_0.geometry} material={materials.Bed_Children_6} material-color={color.Color ? color.Color : null}/>
        <mesh geometry={nodes.Mesh42_Bage_Ceramic10_0.geometry} material={materials.Bage_Ceramic10} material-color={color.Color ? color.Color : null}/>
        <mesh geometry={nodes.Mesh43_Bage_Ceramic10_0.geometry} material={materials.Bage_Ceramic10} material-color={color.Color ? color.Color : null}/>
        <mesh geometry={nodes.Mesh44_Bage_Ceramic10_0.geometry} material={materials.Bage_Ceramic10} material-color={color.Color ? color.Color : null}/>
        <mesh geometry={nodes.Mesh45_Bage_Ceramic10_0.geometry} material={materials.Bage_Ceramic10} material-color={color.Color ? color.Color : null}/>
        <mesh geometry={nodes.Mesh46_Bage_Ceramic10_0.geometry} material={materials.Bage_Ceramic10} material-color={color.Color ? color.Color : null}/>
        <mesh geometry={nodes.Mesh47_Bage_Ceramic10_0.geometry} material={materials.Bage_Ceramic10} material-color={color.Color ? color.Color : null}/>
        <mesh geometry={nodes.Mesh48_Bage_Ceramic10_0.geometry} material={materials.Bage_Ceramic10} material-color={color.Color ? color.Color : null}/>
        <mesh geometry={nodes.Mesh49_Bage_Ceramic10_0.geometry} material={materials.Bage_Ceramic10} material-color={color.Color ? color.Color : null}/>
        <mesh geometry={nodes.Mesh50_Bage_Ceramic10_0.geometry} material={materials.Bage_Ceramic10} material-color={color.Color ? color.Color : null}/>
        <mesh geometry={nodes.Mesh51_Bage_Ceramic10_0.geometry} material={materials.Bage_Ceramic10} material-color={color.Color ? color.Color : null}/>
        <mesh geometry={nodes.Mesh52_Bage_Ceramic10_0.geometry} material={materials.Bage_Ceramic10} />
        <mesh geometry={nodes.Mesh53_Bage_Ceramic10_0.geometry} material={materials.Bage_Ceramic10} />
        <mesh geometry={nodes.Mesh54_Bage_Ceramic10_0.geometry} material={materials.Bage_Ceramic10} />
        <mesh geometry={nodes.Mesh55_Bage_Ceramic10_0.geometry} material={materials.Bage_Ceramic10} />
        <mesh geometry={nodes.Mesh56_Bage_Ceramic10_0.geometry} material={materials.Bage_Ceramic10} />
        <mesh geometry={nodes.Mesh57_Bage_Ceramic10_0.geometry} material={materials.Bage_Ceramic10} />
        <mesh geometry={nodes.Mesh58_Bage_Ceramic10_0.geometry} material={materials.Bage_Ceramic10} />
        <mesh geometry={nodes.Mesh59_Bage_Ceramic10_0.geometry} material={materials.Bage_Ceramic10} />
        <mesh geometry={nodes.Mesh60_Bage_Ceramic10_0.geometry} material={materials.Bage_Ceramic10} />
        <mesh geometry={nodes.Mesh61_Bage_Ceramic10_0.geometry} material={materials.Bage_Ceramic10} />
        <mesh geometry={nodes.Mesh62_Bage_Ceramic10_0.geometry} material={materials.Bage_Ceramic10} />
        <mesh geometry={nodes.Mesh63_Bed_Children_5_0.geometry} material={materials.Bed_Children_5} />
        <mesh geometry={nodes.Mesh64_Bed_Children_5_0.geometry} material={materials.Bed_Children_5} />
        <mesh geometry={nodes.Mesh65_Bed_Children_5_0.geometry} material={materials.Bed_Children_5} />
        <mesh geometry={nodes.Mesh66_Bright_Green_Ceramic_0.geometry} material={materials.Bright_Green_Ceramic} />
        <mesh geometry={nodes.Mesh67_Bright_Green_Ceramic_0.geometry} material={materials.Bright_Green_Ceramic} />
        <mesh geometry={nodes.Mesh69_Aqua_Ceramic_0.geometry} material={materials.Aqua_Ceramic} />
        <mesh geometry={nodes.Mesh70_Bage_Ceramic10_0.geometry} material={materials.Bage_Ceramic10} />
        <mesh geometry={nodes.Mesh71_Bage_Ceramic10_0.geometry} material={materials.Bage_Ceramic10} />
        <mesh geometry={nodes.Mesh72_Bage_Ceramic10_0.geometry} material={materials.Bage_Ceramic10} />
        <mesh geometry={nodes.Mesh73_Bage_Ceramic10_0.geometry} material={materials.Bage_Ceramic10} />
        <mesh geometry={nodes.Mesh74_Bage_Ceramic10_0.geometry} material={materials.Bage_Ceramic10} />
        <mesh geometry={nodes.Mesh75_Bage_Ceramic10_0.geometry} material={materials.Bage_Ceramic10} />
        <mesh geometry={nodes.Mesh76_Bage_Ceramic10_0.geometry} material={materials.Bage_Ceramic10} />
        <mesh geometry={nodes.Mesh77_Bage_Ceramic10_0.geometry} material={materials.Bage_Ceramic10} />
        <mesh geometry={nodes.Mesh78_Bage_Ceramic10_0.geometry} material={materials.Bage_Ceramic10} />
        <mesh geometry={nodes.Mesh79_Bage_Ceramic10_0.geometry} material={materials.Bage_Ceramic10} />
        <mesh geometry={nodes.Mesh80_Bage_Ceramic10_0.geometry} material={materials.Bage_Ceramic10} />
        <mesh geometry={nodes.Mesh81_Bage_Ceramic10_0.geometry} material={materials.Bage_Ceramic10} />
        <mesh geometry={nodes.Mesh82_Bage_Ceramic10_0.geometry} material={materials.Bage_Ceramic10} />
        <mesh geometry={nodes.Mesh83_Bage_Ceramic10_0.geometry} material={materials.Bage_Ceramic10} />
        <mesh geometry={nodes.Mesh84_Bage_Ceramic10_0.geometry} material={materials.Bage_Ceramic10} />
        <mesh geometry={nodes.Mesh85_Bage_Ceramic10_0.geometry} material={materials.Bage_Ceramic10} />
        <mesh geometry={nodes.Mesh86_Bage_Ceramic10_0.geometry} material={materials.Bage_Ceramic10} />
        <mesh geometry={nodes.Mesh2_Bage_Ceramic10_0.geometry} material={materials.Bage_Ceramic10} />
        <mesh geometry={nodes.Mesh3_Bage_Ceramic10_0.geometry} material={materials.Bage_Ceramic10} />
        <mesh geometry={nodes.Mesh4_Bage_Ceramic10_0.geometry} material={materials.Bage_Ceramic10} />
        <mesh geometry={nodes.Mesh5_Bage_Ceramic10_0.geometry} material={materials.Bage_Ceramic10} />
        <mesh geometry={nodes.Mesh6_Bage_Ceramic10_0.geometry} material={materials.Bage_Ceramic10} />
        <mesh geometry={nodes.Mesh7_Bage_Ceramic10_0.geometry} material={materials.Bage_Ceramic10} />
        <mesh geometry={nodes.Mesh8_Bage_Ceramic10_0.geometry} material={materials.Bage_Ceramic10} />
        <mesh geometry={nodes.Mesh9_Blue_Purple_Ceramic_0.geometry} material={materials.Blue_Purple_Ceramic} />
        <mesh geometry={nodes.Mesh10_Bage_Ceramic10_0.geometry} material={materials.Bage_Ceramic10} />
        <mesh geometry={nodes.Mesh11_Bage_Ceramic10_0.geometry} material={materials.Bage_Ceramic10} />
        <mesh geometry={nodes.Mesh12_Bage_Ceramic10_0.geometry} material={materials.Bage_Ceramic10} />
        <mesh geometry={nodes.Mesh13_Bage_Ceramic10_0.geometry} material={materials.Bage_Ceramic10} />
        <mesh geometry={nodes.Mesh14_Bage_Ceramic10_0.geometry} material={materials.Bage_Ceramic10} />
        <mesh geometry={nodes.Mesh15_Bage_Ceramic10_0.geometry} material={materials.Bage_Ceramic10} />
        <mesh geometry={nodes.Mesh16_Bage_Ceramic10_0.geometry} material={materials.Bage_Ceramic10} />
        <mesh geometry={nodes.Mesh17_Bage_Ceramic10_0.geometry} material={materials.Bage_Ceramic10} />
        <mesh geometry={nodes.Mesh18_Bage_Ceramic10_0.geometry} material={materials.Bage_Ceramic10} />
        <mesh geometry={nodes.Mesh19_Bage_Ceramic10_0.geometry} material={materials.Bage_Ceramic10} />
        <mesh geometry={nodes.Mesh20_Bage_Ceramic10_0.geometry} material={materials.Bage_Ceramic10} />
        <mesh geometry={nodes.Mesh21_Bage_Ceramic10_0.geometry} material={materials.Bage_Ceramic10} />
        <mesh geometry={nodes.Mesh22_Bage_Ceramic10_0.geometry} material={materials.Bage_Ceramic10} />
        <mesh geometry={nodes.Mesh23_Bage_Ceramic10_0.geometry} material={materials.Bage_Ceramic10} />
        <mesh geometry={nodes.Mesh24_Bage_Ceramic10_0.geometry} material={materials.Bage_Ceramic10} />
        <mesh geometry={nodes.Mesh25_Bage_Ceramic10_0.geometry} material={materials.Bage_Ceramic10} />
        <mesh geometry={nodes.Mesh26_Bage_Ceramic10_0.geometry} material={materials.Bage_Ceramic10} />
        <mesh geometry={nodes.Mesh27_Baby_Blue_Ceramic1_0.geometry} material={materials.Baby_Blue_Ceramic1} />
        <mesh geometry={nodes.Mesh28_Bed_Children_5_0.geometry} material={materials.Bed_Children_5} />
        <mesh geometry={nodes.Mesh29_Baby_Blue_Ceramic1_0.geometry} material={materials.Baby_Blue_Ceramic1} />
        <mesh geometry={nodes.Mesh30_Bed_Children_5_0.geometry} material={materials.Bed_Children_5} />
        <mesh geometry={nodes.Mesh31_Bed_Children_5_0.geometry} material={materials.Bed_Children_5} />
      </group>
    </group>
  )
});

useGLTF.preload('/bed6.glb');

export default Bed6;
