/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.12 bed7.glb
*/

import React, { useRef, forwardRef } from 'react';
import { useGLTF } from '@react-three/drei';

const Bed7 = forwardRef(({ events, props, action, rotate, color }, ref) => {
  const { nodes, materials } = useGLTF('/bed7.glb')
  return (
    <group
      dispose={null}
      {...props}
      {...events}
      ref={ref}
      onClick={action}
      rotation-y={rotate}
    >
      <group position={[20.2, 112.541, -112.541]} rotation={[0, 0, Math.PI]}>
        <mesh geometry={nodes.Object_10.geometry} material={materials['2335422']} material-color={color.Pillow ? color.Pillow : null}/>
        <mesh geometry={nodes.Object_11.geometry} material={materials.Bogemia_Milk} />
        <mesh geometry={nodes.Object_12.geometry} material={materials.Bogemia_Milk} />
        <mesh geometry={nodes.Object_13.geometry} material={materials.Bogemia_Milk} />
        <mesh geometry={nodes.Object_14.geometry} material={materials.Bogemia_Milk} material-color={color.Body ? color.Body : null}/>
        <mesh geometry={nodes.Object_15.geometry} material={materials.Bogemia_Milk} />
        <mesh geometry={nodes.Object_16.geometry} material={materials.Bogemia_Milk} />
        <mesh geometry={nodes.Object_17.geometry} material={materials.Bogemia_Milk} />
        <mesh geometry={nodes.Object_18.geometry} material={materials.Gold255}/>
        <mesh geometry={nodes.Object_19.geometry} material={materials.Gold255} />
        <mesh geometry={nodes.Object_2.geometry} material={materials['2332244']} />
        <mesh geometry={nodes.Object_20.geometry} material={materials.Gold255} />
        <mesh geometry={nodes.Object_21.geometry} material={materials.Gold255} />
        <mesh geometry={nodes.Object_22.geometry} material={materials.Gold255} material-color={color.Mattress ? color.Mattress : null}/>
        <mesh geometry={nodes.Object_23.geometry} material={materials.Gold255} />
        <mesh geometry={nodes.Object_24.geometry} material={materials.Gold255} />
        <mesh geometry={nodes.Object_3.geometry} material={materials['2332']} />
        <mesh geometry={nodes.Object_4.geometry} material={materials['2332']} />
        <mesh geometry={nodes.Object_5.geometry} material={materials['2335422']} />
        <mesh geometry={nodes.Object_6.geometry} material={materials['2335422']} />
        <mesh geometry={nodes.Object_7.geometry} material={materials['2335422']} />
        <mesh geometry={nodes.Object_8.geometry} material={materials['2335422']} />
        <mesh geometry={nodes.Object_9.geometry} material={materials['2335422']} />
      </group>
    </group>
  )
});

useGLTF.preload('/bed7.glb');

export default Bed7;

