/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.12 bed9.glb
*/

import React, { useRef, forwardRef } from 'react';
import { useGLTF } from '@react-three/drei';

const Bed9 = forwardRef(({ events, props, action, rotate, color }, ref) => {
  const { nodes, materials } = useGLTF('/bed9.glb')
  return (
    <group
      dispose={null}
      {...props}
      {...events}
      ref={ref}
      onClick={action}
      rotation-y={rotate}
    >
      <group rotation={[-Math.PI / 2, 0, 0]} scale={0.02}>
        <group scale={100}>
          <mesh geometry={nodes.Bed_Blanket_0.geometry} material={materials.Blanket} material-color={color.Blanket ? color.Blanket : null}/>
          <mesh geometry={nodes.Bed_Matress_0.geometry} material={materials.Matress} material-color={color.Mattress ? color.Mattress : null}/>
          <mesh geometry={nodes.Bed_Pillow001_0.geometry} material={materials['Pillow.001']} material-color={color.Pillow ? color.Pillow : null}/>
          <mesh geometry={nodes.Bed_Pillow002_0.geometry} material={materials['Pillow.002']} material-color={color.Pillow ? color.Pillow : null}/>
          <mesh geometry={nodes.Bed_Pillow003_0.geometry} material={materials['Pillow.003']} material-color={color.Pillow ? color.Pillow : null}/>
          <mesh geometry={nodes.Bed_Sheet_0.geometry} material={materials.Sheet} material-color={color.Sheet ? color.Sheet : null}/>
          <mesh geometry={nodes.Bed_Wood_0.geometry} material={materials.Wood} material-color={color.Wood ? color.Wood : null}/>
        </group>
      </group>
    </group>
  )
});

useGLTF.preload('/bed9.glb');

export default Bed9;

