/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.15 1br.glb 
*/

import React, { useRef } from 'react';
import { useGLTF } from '@react-three/drei';

export default function Unit1br(props) {
	const { nodes, materials } = useGLTF('/1br.glb');
	return (
		<group
			{...props}
			dispose={null}
		>
			<mesh
				geometry={nodes.rightwall.geometry}
				material={materials.Material}
				position={[2.353, 1, -2.007]}
			/>
			<mesh
				geometry={nodes.leftwall.geometry}
				material={materials.Material}
				position={[-4.222, 1, -2.007]}
			/>
			<mesh
				geometry={nodes.backwall.geometry}
				material={materials.Material}
				position={[-2.226, 1, -2.008]}
				rotation={[0, 1.571, 0]}
			/>
			<mesh
				geometry={nodes.floor.geometry}
				material={materials['271F1F']}
			/>
			<mesh
				geometry={nodes.middlewall.geometry}
				material={materials.Material}
				position={[-0.942, 1, -1.9]}
			/>
			<mesh
				geometry={nodes.middlewall2.geometry}
				material={materials.Material}
				position={[-0.936, 1, -0.437]}
			/>
			<mesh
				geometry={nodes.entrywall.geometry}
				material={materials.Material}
				position={[-1.672, 1, 2.106]}
				rotation={[-Math.PI, 1.565, -Math.PI]}
			/>
			<mesh
				geometry={nodes.crwall.geometry}
				material={materials.Material}
				position={[-2.417, 1, -0.436]}
			/>
			<mesh
				geometry={nodes.frontwall.geometry}
				material={materials.Material}
				position={[-2.22, 1, 3.893]}
				rotation={[0, 1.571, 0]}
			/>
			<mesh
				geometry={nodes.leftentrywall.geometry}
				material={materials.Material}
				position={[-2.417, 1, 1.371]}
			/>
			<mesh
				geometry={nodes.kitchenwall.geometry}
				material={materials.Material}
				position={[-0.927, 1, 1.345]}
			/>
			<mesh
				geometry={nodes.brwall.geometry}
				material={materials.Material}
				position={[-3.39, 1, 1.436]}
				rotation={[-Math.PI, 1.565, -Math.PI]}
			/>
			<mesh
				geometry={nodes.frontwall2.geometry}
				material={materials.Material}
				position={[-3.256, 1, 3.908]}
				rotation={[-Math.PI, 1.565, -Math.PI]}
			/>
			<mesh
				geometry={nodes.sinktable001.geometry}
				material={materials['Material.008']}
				position={[0.797, 0.43, 2.837]}
			/>
			<mesh
				geometry={nodes.sinkhandle2.geometry}
				material={nodes.sinkhandle2.material}
				position={[1.84, 0.829, 2.877]}
				scale={0.015}
			/>
			<mesh
				geometry={nodes.sinkHandle.geometry}
				material={nodes.sinkHandle.material}
				position={[1.98, 0.827, 2.877]}
				scale={0.015}
			/>
			<mesh
				geometry={nodes.kitchensink.geometry}
				material={materials['Material.001']}
				position={[1.932, 0.828, 2.593]}
				rotation={[Math.PI, -1.568, Math.PI]}
				scale={0.3}
			/>
			<mesh
				geometry={nodes.kitchenSink.geometry}
				material={nodes.kitchenSink.material}
				position={[1.908, 0.83, 2.878]}
				rotation={[0.22, 1.458, -0.212]}
				scale={[0.024, 0.027, 0.024]}
			/>
			<mesh
				geometry={nodes.sinktable002.geometry}
				material={materials['Material.008']}
				position={[-0.167, 0.43, 2.829]}
			/>
			<mesh
				geometry={nodes.sinktable003.geometry}
				material={materials['Material.008']}
				position={[1.99, 0.43, 2.829]}
			/>
			<mesh
				geometry={nodes.smallCabinet.geometry}
				material={materials['987859']}
				position={[1.807, 1.597, 2.843]}
			/>
			<mesh
				geometry={nodes.smallcabhandle2.geometry}
				material={nodes.smallcabhandle2.material}
				position={[3.462, 1.379, 3.358]}
			/>
			<mesh
				geometry={nodes.smallcabhandle.geometry}
				material={nodes.smallcabhandle.material}
				position={[3.413, 1.379, 3.358]}
			/>
			<mesh
				geometry={nodes.mediumcabinet.geometry}
				material={materials['987859']}
				position={[1.221, 1.595, 2.842]}
			/>
			<mesh
				geometry={nodes.medcabhandle2.geometry}
				material={nodes.medcabhandle2.material}
				position={[2.899, 1.263, 3.358]}
			/>
			<mesh
				geometry={nodes.medcabhandle.geometry}
				material={nodes.medcabhandle.material}
				position={[2.826, 1.263, 3.358]}
			/>
			<mesh
				geometry={nodes.longcabinet.geometry}
				material={materials['987859']}
				position={[0.622, 1.595, 2.843]}
			/>
			<mesh
				geometry={nodes.longcabhandle2.geometry}
				material={nodes.longcabhandle2.material}
				position={[2.123, 1.379, 3.358]}
			/>
			<mesh
				geometry={nodes.longcabhandle.geometry}
				material={nodes.longcabhandle.material}
				position={[2.062, 1.379, 3.358]}
			/>
			<mesh
				geometry={nodes.longcabinet001.geometry}
				material={materials['987859']}
				position={[-0.293, 1.595, 2.843]}
			/>
			<mesh
				geometry={nodes.longcabhandle2001.geometry}
				material={nodes.longcabhandle2001.material}
				position={[1.138, 1.379, 3.358]}
			/>
			<mesh
				geometry={nodes.longcabhandle001.geometry}
				material={nodes.longcabhandle001.material}
				position={[1.076, 1.379, 3.358]}
			/>
			<mesh
				geometry={nodes.longcabhandle2002.geometry}
				material={nodes.longcabhandle2002.material}
				position={[1.078, 0.052, 3.144]}
			/>
			<mesh
				geometry={nodes.longcabhandle002.geometry}
				material={nodes.longcabhandle002.material}
				position={[1.017, 0.052, 3.144]}
			/>
			<mesh
				geometry={nodes.longcabhandle2003.geometry}
				material={nodes.longcabhandle2003.material}
				position={[3.265, 0.052, 3.144]}
			/>
			<mesh
				geometry={nodes.longcabhandle003.geometry}
				material={nodes.longcabhandle003.material}
				position={[3.203, 0.052, 3.144]}
			/>
			<mesh
				geometry={nodes.showerGlass.geometry}
				material={materials.Material}
				position={[-3.212, 1.014, 1.223]}
				rotation={[Math.PI, -1.564, Math.PI]}
			/>
			<mesh
				geometry={nodes.toilet.geometry}
				material={nodes.toilet.material}
				position={[-2.997, 0.252, 0.912]}
				rotation={[0, 0.008, 0]}
				scale={0.223}
			/>
			<mesh
				geometry={nodes.taphandle001.geometry}
				material={nodes.taphandle001.material}
				position={[-3.165, 0.851, 1.68]}
				rotation={[-Math.PI, 0.023, -Math.PI]}
				scale={[0.023, 0.065, 0.023]}
			/>
			<mesh
				geometry={nodes.tap001.geometry}
				material={nodes.tap001.material}
				position={[-3.165, 0.85, 1.68]}
				rotation={[-Math.PI, 0.023, -Math.PI]}
				scale={[0.023, 0.065, 0.023]}
			/>
			<mesh
				geometry={nodes.sinktable004.geometry}
				material={materials['Material.007']}
				position={[-2.33, 0.504, 1.808]}
				rotation={[0, 1.57, 0]}
			/>
			<mesh
				geometry={nodes.sinkCabinet001.geometry}
				material={materials['Material.006']}
				position={[-2.326, 0.363, 1.727]}
				rotation={[0, 1.57, 0]}
			/>
			<mesh
				geometry={nodes.sinkcabHandle2001.geometry}
				material={nodes.sinkcabHandle2001.material}
				position={[-1.922, 0.313, 1.102]}
				rotation={[0, 1.57, 0]}
			/>
			<mesh
				geometry={nodes.sinkcabHandle001.geometry}
				material={nodes.sinkcabHandle001.material}
				position={[-1.922, 0.315, 1.179]}
				rotation={[0, 1.57, 0]}
			/>
			<mesh
				geometry={nodes.crsink001.geometry}
				material={nodes.crsink001.material}
				position={[-2.963, 0.719, 1.683]}
				rotation={[Math.PI, 0, Math.PI]}
				scale={[0.051, 0.067, 0.294]}
			/>
			<mesh
				geometry={nodes.showrebase.geometry}
				material={materials['Material.004']}
				position={[-3.211, 1.499, 2.637]}
				rotation={[Math.PI, -0.001, -1.57]}
				scale={0.075}
			/>
			<mesh
				geometry={nodes.showerhead.geometry}
				material={materials['Material.004']}
				position={[-2.759, 1.439, 2.636]}
				rotation={[Math.PI, -0.001, -0.003]}
				scale={0.075}
			/>
			<mesh
				geometry={nodes.showerbody.geometry}
				material={nodes.showerbody.material}
				position={[-2.764, 1.462, 2.637]}
				rotation={[Math.PI, -0.001, Math.PI]}
				scale={0.015}
			/>
			<mesh
				geometry={nodes.shower.geometry}
				material={materials['Material.004']}
				position={[-3.187, 1.499, 2.637]}
				rotation={[Math.PI, -0.001, Math.PI]}
				scale={0.021}
			/>
			<mesh
				geometry={nodes.tallCabinet.geometry}
				material={materials['987859']}
				position={[-0.517, 0.428, 1.04]}
			/>
			<mesh
				geometry={nodes.tallcabHandle2.geometry}
				material={nodes.tallcabHandle2.material}
				position={[-0.187, 0.853, 1.362]}
			/>
			<mesh
				geometry={nodes.tallcabHandle.geometry}
				material={nodes.tallcabHandle.material}
				position={[-0.27, 0.85, 1.362]}
			/>
			<group
				position={[2.76, 0.985, -1.918]}
				rotation={[0, 1.563, 0]}
			>
				<mesh
					geometry={nodes.Cube049.geometry}
					material={materials['Material.003']}
				/>
				<mesh
					geometry={nodes.Cube049_1.geometry}
					material={materials.window}
				/>
			</group>
			<group
				position={[-0.583, 0.985, -1.918]}
				rotation={[0, 1.563, 0]}
			>
				<mesh
					geometry={nodes.Cube050.geometry}
					material={materials['Material.002']}
				/>
				<mesh
					geometry={nodes.Cube050_1.geometry}
					material={materials['window.001']}
				/>
			</group>
			<mesh
				geometry={nodes.Text.geometry}
				material={materials['271F1F']}
				position={[3.387, 0.116, 2.974]}
				rotation={[Math.PI / 2, 0, -Math.PI / 2]}
				scale={0.403}
			/>
			<mesh
				geometry={nodes.Text001.geometry}
				material={materials['271F1F']}
				position={[-3.353, 0.116, -2.931]}
				rotation={[Math.PI / 2, 0, 1.573]}
				scale={0.403}
			/>
			<mesh
				geometry={nodes.Text002.geometry}
				material={materials['271F1F']}
				position={[3.145, 0.124, -3.006]}
				rotation={[Math.PI / 2, 0, Math.PI]}
				scale={0.436}
			/>
			<mesh
				geometry={nodes.Text003.geometry}
				material={materials['271F1F']}
				position={[-0.378, 0.094, 3.017]}
				rotation={[Math.PI / 2, 0, 0]}
				scale={0.398}
			/>
		</group>
	);
}

useGLTF.preload('/1br.glb');
