/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.15 2br.glb 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Unit2br(props) {
  const { nodes, materials } = useGLTF('/2br.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.floor.geometry} material={materials.floors} />
      <mesh geometry={nodes.leftwall.geometry} material={materials.walls} position={[2.789, 1.015, 2.437]} />
      <mesh geometry={nodes.rightwall.geometry} material={materials.walls} position={[2.789, 1.015, -4.935]} />
      <mesh geometry={nodes.frontwall.geometry} material={materials.walls} position={[2.803, 1.014, -3.043]} rotation={[-Math.PI, 1.564, -Math.PI]} />
      <mesh geometry={nodes.b1wall.geometry} material={materials.walls} position={[-4.604, 1.014, -3.043]} rotation={[-Math.PI, 1.564, -Math.PI]} />
      <mesh geometry={nodes.salawall.geometry} material={materials.walls} position={[-0.901, 1.014, -3.043]} rotation={[-Math.PI, 1.564, -Math.PI]} />
      <mesh geometry={nodes.leftcrwall.geometry} material={materials.walls} position={[1.772, 1.023, -2.38]} />
      <mesh geometry={nodes.backwall.geometry} material={materials.walls} position={[-5.611, 1.014, -0.487]} rotation={[-Math.PI, 1.564, -Math.PI]} />
      <mesh geometry={nodes.b2swall.geometry} material={materials.walls} position={[1.795, 1.006, 1.342]} />
      <mesh geometry={nodes.b2mwall.geometry} material={materials.walls} position={[-4.6, 1.014, 0.585]} rotation={[-Math.PI, 1.564, -Math.PI]} />
      <mesh geometry={nodes.crleftwall.geometry} material={materials.walls} position={[1.795, 1.006, -0.648]} />
      <mesh geometry={nodes.b2wall.geometry} material={materials.walls} position={[-0.901, 1.014, 1.678]} rotation={[-Math.PI, 1.564, -Math.PI]} />
      <mesh geometry={nodes.entrancewall.geometry} material={materials.walls} position={[10.174, 1.006, 0.344]} />
      <mesh geometry={nodes.leftentrancewall.geometry} material={materials.walls} position={[4.019, 1.014, -0.402]} rotation={[-Math.PI, 1.564, -Math.PI]} />
      <mesh geometry={nodes.rightentrancewall.geometry} material={materials.walls} position={[4.019, 1.014, 1.196]} rotation={[-Math.PI, 1.564, -Math.PI]} />
      <mesh geometry={nodes.backfloor.geometry} material={materials.floors} position={[-3.623, 0, -0.228]} />
      <mesh geometry={nodes.entryfloor.geometry} material={materials.floors} position={[4.793, 0.01, 2.376]} />
      <mesh geometry={nodes.crentrywall.geometry} material={materials.walls} position={[-1.994, 1.014, -2.988]} rotation={[-Math.PI, 1.564, -Math.PI]} />
      <mesh geometry={nodes.showerGlass.geometry} material={materials.walls} position={[-4.224, 1.014, -0.411]} rotation={[0, -0.013, 0]} />
      <mesh geometry={nodes.taphandle001.geometry} material={nodes.taphandle001.material} position={[-1.665, 0.851, -1.332]} rotation={[0, 1.548, 0]} scale={[0.023, 0.065, 0.023]} />
      <mesh geometry={nodes.tap001.geometry} material={nodes.tap001.material} position={[-1.665, 0.85, -1.332]} rotation={[0, 1.548, 0]} scale={[0.023, 0.065, 0.023]} />
      <mesh geometry={nodes.sinktable004.geometry} material={materials.AAAAAA} position={[-1.793, 0.504, -0.497]} rotation={[0, -0.001, 0]} />
      <mesh geometry={nodes.sinkCabinet001.geometry} material={materials['Material.006']} position={[-1.711, 0.363, -0.492]} rotation={[0, -0.001, 0]} />
      <mesh geometry={nodes.sinkcabHandle2001.geometry} material={nodes.sinkcabHandle2001.material} position={[-1.087, 0.313, -0.088]} rotation={[0, -0.001, 0]} />
      <mesh geometry={nodes.sinkcabHandle001.geometry} material={nodes.sinkcabHandle001.material} position={[-1.163, 0.315, -0.088]} rotation={[0, -0.001, 0]} />
      <mesh geometry={nodes.crsink001.geometry} material={nodes.crsink001.material} position={[-1.668, 0.719, -1.13]} rotation={[0, 1.571, 0]} scale={[0.051, 0.067, 0.294]} />
      <mesh geometry={nodes.toilet.geometry} material={nodes.toilet.material} position={[-2.639, 0.269, -1.148]} rotation={[0, -1.568, 0]} scale={0.223} />
      <mesh geometry={nodes.showrebase.geometry} material={materials.AAAAAA} position={[-3.838, 1.746, -1.354]} rotation={[0, 1.569, 1.572]} scale={0.075} />
      <mesh geometry={nodes.showerhead.geometry} material={materials.AAAAAA} position={[-3.839, 1.686, -0.902]} rotation={[0, 1.569, 3.139]} scale={0.075} />
      <mesh geometry={nodes.showerbody.geometry} material={nodes.showerbody.material} position={[-3.839, 1.709, -0.907]} rotation={[0, 1.569, 0]} scale={0.015} />
      <mesh geometry={nodes.shower.geometry} material={materials.AAAAAA} position={[-3.839, 1.746, -1.33]} rotation={[0, 1.569, 0]} scale={0.021} />
      <mesh geometry={nodes.sinktable002.geometry} material={materials['Material.004']} position={[-0.132, 0.43, 3.253]} />
      <mesh geometry={nodes.sinktable001.geometry} material={materials['Material.004']} position={[0.806, 0.43, 3.252]} />
      <mesh geometry={nodes.sinkhandle2.geometry} material={nodes.sinkhandle2.material} position={[1.849, 0.829, 3.292]} scale={0.015} />
      <mesh geometry={nodes.sinkHandle.geometry} material={nodes.sinkHandle.material} position={[1.989, 0.827, 3.292]} scale={0.015} />
      <mesh geometry={nodes.kitchenSink.geometry} material={nodes.kitchenSink.material} position={[1.917, 0.83, 3.293]} rotation={[0.22, 1.458, -0.212]} scale={[0.024, 0.027, 0.024]} />
      <mesh geometry={nodes.kitchensink.geometry} material={materials['Material.001']} position={[1.941, 0.828, 3.008]} rotation={[Math.PI, -1.568, Math.PI]} scale={0.3} />
      <mesh geometry={nodes.sinkwall.geometry} material={materials.walls} position={[2.203, 1.014, 1.066]} rotation={[-Math.PI, 1.564, -Math.PI]} />
      <mesh geometry={nodes.sinktable003.geometry} material={materials['Material.004']} position={[0.165, 0.43, 1.519]} rotation={[0, -1.566, 0]} />
      <mesh geometry={nodes.longcabhandle2002.geometry} material={nodes.longcabhandle2002.material} position={[-0.143, 0.052, 2.766]} rotation={[0, -1.566, 0]} />
      <mesh geometry={nodes.longcabhandle002.geometry} material={nodes.longcabhandle002.material} position={[-0.143, 0.052, 2.704]} rotation={[0, -1.566, 0]} />
      <mesh geometry={nodes.sinktable005.geometry} material={materials['Material.004']} position={[0.165, 0.43, 0.559]} rotation={[0, -1.566, 0]} />
      <mesh geometry={nodes.longcabhandle2001.geometry} material={nodes.longcabhandle2001.material} position={[-0.143, 0.052, 1.806]} rotation={[0, -1.566, 0]} />
      <mesh geometry={nodes.longcabhandle001.geometry} material={nodes.longcabhandle001.material} position={[-0.143, 0.052, 1.744]} rotation={[0, -1.566, 0]} />
      <mesh geometry={nodes.diningwall.geometry} material={materials.walls} position={[6.601, 1.006, -0.082]} />
      <mesh geometry={nodes.smallCabinet.geometry} material={materials.canb} position={[0.141, 1.596, 1.581]} rotation={[-0.483, -1.564, -0.481]} />
      <mesh geometry={nodes.smallcabhandle2.geometry} material={nodes.smallcabhandle2.material} position={[-0.37, 1.409, 3.24]} rotation={[-1.365, -1.54, -1.363]} />
      <mesh geometry={nodes.smallcabhandle.geometry} material={nodes.smallcabhandle.material} position={[-0.37, 1.409, 3.191]} rotation={[-1.365, -1.54, -1.363]} />
      <mesh geometry={nodes.mediumcabinet.geometry} material={materials.canb} position={[0.138, 1.605, 0.996]} rotation={[-1.109, -1.557, -1.107]} />
      <mesh geometry={nodes.medcabhandle2.geometry} material={nodes.medcabhandle2.material} position={[-0.377, 1.291, 2.678]} rotation={[-1.365, -1.54, -1.363]} />
      <mesh geometry={nodes.medcabhandle.geometry} material={nodes.medcabhandle.material} position={[-0.378, 1.291, 2.605]} rotation={[-1.365, -1.54, -1.363]} />
      <mesh geometry={nodes.longcabinet.geometry} material={materials.canb} position={[0.133, 1.603, 0.396]} rotation={[-1.109, -1.557, -1.107]} />
      <mesh geometry={nodes.longcabhandle2.geometry} material={nodes.longcabhandle2.material} position={[-0.379, 1.406, 1.901]} rotation={[-1.365, -1.54, -1.363]} />
      <mesh geometry={nodes.longcabhandle.geometry} material={nodes.longcabhandle.material} position={[-0.379, 1.406, 1.84]} rotation={[-1.365, -1.54, -1.363]} />
      <mesh geometry={nodes.longcabinet001.geometry} material={materials.canb} position={[-0.094, 1.605, 3.246]} />
      <mesh geometry={nodes.longcabinet002.geometry} material={materials.canb} position={[0.821, 1.598, 3.246]} />
      <mesh geometry={nodes.longcabhandle2003.geometry} material={nodes.longcabhandle2003.material} position={[1.337, 1.383, 3.762]} />
      <mesh geometry={nodes.longcabhandle2004.geometry} material={nodes.longcabhandle2004.material} position={[2.323, 1.383, 3.762]} />
      <mesh geometry={nodes.longcabhandle003.geometry} material={nodes.longcabhandle003.material} position={[1.276, 1.383, 3.762]} />
      <mesh geometry={nodes.longcabhandle004.geometry} material={nodes.longcabhandle004.material} position={[2.262, 1.383, 3.762]} />
      <group position={[-3.629, 0.987, 0.199]} rotation={[-Math.PI, 0.011, -Math.PI]}>
        <mesh geometry={nodes.Cube050.geometry} material={materials['Material.003']} />
        <mesh geometry={nodes.Cube050_1.geometry} material={materials.window} />
      </group>
      <group position={[-2.628, 0.987, -3.775]} rotation={[-Math.PI, 0.011, -Math.PI]}>
        <mesh geometry={nodes.Cube051.geometry} material={materials['Material.002']} />
        <mesh geometry={nodes.Cube051_1.geometry} material={materials['window.001']} />
      </group>
      <mesh geometry={nodes.Text.geometry} material={materials.floors} position={[-3.68, 0.177, 3.437]} rotation={[Math.PI / 2, 0, 0]} scale={0.408} />
      <mesh geometry={nodes.Text001.geometry} material={materials.floors} position={[-4.743, 0.172, -1.477]} rotation={[Math.PI / 2, 0, Math.PI / 2]} scale={0.37} />
      <mesh geometry={nodes.Text002.geometry} material={materials.floors} position={[-3.731, 0.139, -4.015]} rotation={[Math.PI / 2, 0, Math.PI / 2]} scale={0.402} />
      <mesh geometry={nodes.Text003.geometry} material={materials.floors} position={[3.746, 0.154, -4.072]} rotation={[Math.PI / 2, 0, -Math.PI]} scale={0.607} />
      <mesh geometry={nodes.Text004.geometry} material={materials.floors} position={[3.799, 0.158, 1.341]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={0.478} />
    </group>
  )
}

useGLTF.preload('/2br.glb')
