/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.15 2brBig.glb 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Unit2brBig(props) {
  const { nodes, materials } = useGLTF('/2brBig.glb')
  return (
    <group {...props} dispose={null}>
      <group position={[-0.583, 0.985, -1.918]} rotation={[0, 1.563, 0]}>
        <mesh geometry={nodes.Cube050.geometry} material={materials['Material.001']} />
        <mesh geometry={nodes.Cube050_1.geometry} material={materials['window.001']} />
      </group>
      <group position={[2.76, 0.985, -1.918]} rotation={[0, 1.563, 0]}>
        <mesh geometry={nodes.Cube049.geometry} material={materials['Material.001']} />
        <mesh geometry={nodes.Cube049_1.geometry} material={materials.window} />
      </group>
      <mesh geometry={nodes.toilet001.geometry} material={nodes.toilet001.material} position={[6.364, 0.252, 0.912]} rotation={[Math.PI, -0.007, Math.PI]} scale={0.223} />
      <mesh geometry={nodes.toilet.geometry} material={nodes.toilet.material} position={[-2.997, 0.252, 0.912]} rotation={[0, 0.008, 0]} scale={0.223} />
      <mesh geometry={nodes.taphandle002.geometry} material={nodes.taphandle002.material} position={[6.536, 0.851, 1.687]} rotation={[0, -0.02, 0]} scale={[0.023, 0.065, 0.023]} />
      <mesh geometry={nodes.taphandle001.geometry} material={nodes.taphandle001.material} position={[-3.165, 0.851, 1.68]} rotation={[-Math.PI, 0.023, -Math.PI]} scale={[0.023, 0.065, 0.023]} />
      <mesh geometry={nodes.tap002.geometry} material={nodes.tap002.material} position={[6.536, 0.85, 1.687]} rotation={[0, -0.02, 0]} scale={[0.023, 0.065, 0.023]} />
      <mesh geometry={nodes.tap001.geometry} material={nodes.tap001.material} position={[-3.165, 0.85, 1.68]} rotation={[-Math.PI, 0.023, -Math.PI]} scale={[0.023, 0.065, 0.023]} />
      <mesh geometry={nodes.tallCabinet.geometry} material={materials.Cabinet} position={[-0.517, 0.428, 1.04]} />
      <mesh geometry={nodes.tallcabHandle2.geometry} material={nodes.tallcabHandle2.material} position={[-0.187, 0.853, 1.362]} />
      <mesh geometry={nodes.tallcabHandle.geometry} material={nodes.tallcabHandle.material} position={[-0.27, 0.85, 1.362]} />
      <mesh geometry={nodes.smallCabinet.geometry} material={materials.Cabinet} position={[1.807, 1.597, 2.843]} />
      <mesh geometry={nodes.smallcabhandle2.geometry} material={nodes.smallcabhandle2.material} position={[3.462, 1.379, 3.358]} />
      <mesh geometry={nodes.smallcabhandle.geometry} material={nodes.smallcabhandle.material} position={[3.413, 1.379, 3.358]} />
      <mesh geometry={nodes.sinktable005.geometry} material={materials.SinkTop} position={[5.701, 0.504, 1.561]} rotation={[0, -1.569, 0]} />
      <mesh geometry={nodes.sinktable004.geometry} material={materials.SinkTop} position={[-2.33, 0.504, 1.808]} rotation={[0, 1.57, 0]} />
      <mesh geometry={nodes.sinktable003.geometry} material={materials.Sink} position={[1.99, 0.43, 2.829]} />
      <mesh geometry={nodes.sinktable002.geometry} material={materials.Sink} position={[-0.167, 0.43, 2.829]} />
      <mesh geometry={nodes.sinktable001.geometry} material={materials.Sink} position={[0.797, 0.43, 2.837]} />
      <mesh geometry={nodes.sinkhandle2.geometry} material={nodes.sinkhandle2.material} position={[1.84, 0.829, 2.877]} scale={0.015} />
      <mesh geometry={nodes.sinkHandle.geometry} material={nodes.sinkHandle.material} position={[1.98, 0.827, 2.877]} scale={0.015} />
      <mesh geometry={nodes.sinkCabinet002.geometry} material={materials['Material.006']} position={[5.696, 0.363, 1.642]} rotation={[0, -1.569, 0]} />
      <mesh geometry={nodes.sinkCabinet001.geometry} material={materials.Sink} position={[-2.326, 0.363, 1.727]} rotation={[0, 1.57, 0]} />
      <mesh geometry={nodes.sinkcabHandle2002.geometry} material={nodes.sinkcabHandle2002.material} position={[5.294, 0.313, 2.268]} rotation={[0, -1.569, 0]} />
      <mesh geometry={nodes.sinkcabHandle2001.geometry} material={nodes.sinkcabHandle2001.material} position={[-1.922, 0.313, 1.102]} rotation={[0, 1.57, 0]} />
      <mesh geometry={nodes.sinkcabHandle002.geometry} material={nodes.sinkcabHandle002.material} position={[5.294, 0.315, 2.192]} rotation={[0, -1.569, 0]} />
      <mesh geometry={nodes.sinkcabHandle001.geometry} material={nodes.sinkcabHandle001.material} position={[-1.922, 0.315, 1.179]} rotation={[0, 1.57, 0]} />
      <mesh geometry={nodes.showrebase001.geometry} material={materials.Shower} position={[6.576, 1.499, 2.638]} rotation={[0, -0.006, 1.572]} scale={0.075} />
      <mesh geometry={nodes.showrebase.geometry} material={materials.Shower} position={[-3.211, 1.499, 2.637]} rotation={[Math.PI, -0.001, -1.57]} scale={0.075} />
      <mesh geometry={nodes.showerhead001.geometry} material={materials.Shower} position={[6.125, 1.439, 2.636]} rotation={[0, -0.006, 3.139]} scale={0.075} />
      <mesh geometry={nodes.showerhead.geometry} material={materials.Shower} position={[-2.759, 1.439, 2.636]} rotation={[Math.PI, -0.001, -0.003]} scale={0.075} />
      <mesh geometry={nodes.showerGlass001.geometry} material={materials.Walls} position={[5.611, 1.014, 1.223]} rotation={[Math.PI, -1.564, Math.PI]} />
      <mesh geometry={nodes.showerGlass.geometry} material={materials.Walls} position={[-3.212, 1.014, 1.223]} rotation={[Math.PI, -1.564, Math.PI]} />
      <mesh geometry={nodes.showerbody001.geometry} material={nodes.showerbody001.material} position={[6.13, 1.462, 2.635]} rotation={[0, -0.006, 0]} scale={0.015} />
      <mesh geometry={nodes.showerbody.geometry} material={nodes.showerbody.material} position={[-2.764, 1.462, 2.637]} rotation={[Math.PI, -0.001, Math.PI]} scale={0.015} />
      <mesh geometry={nodes.shower001.geometry} material={materials.Shower} position={[6.553, 1.499, 2.638]} rotation={[0, -0.006, 0]} scale={0.021} />
      <mesh geometry={nodes.shower.geometry} material={materials.Shower} position={[-3.187, 1.499, 2.637]} rotation={[Math.PI, -0.001, Math.PI]} scale={0.021} />
      <mesh geometry={nodes.rightwall001.geometry} material={materials.Walls} position={[5.696, 1, -2.007]} />
      <mesh geometry={nodes.rightwall.geometry} material={materials.Walls} position={[2.353, 1, -2.007]} />
      <mesh geometry={nodes.Plane.geometry} material={materials.Floors} position={[4.358, 0.01, 1.991]} />
      <mesh geometry={nodes.middlewall2.geometry} material={materials.Walls} position={[-0.936, 1, -0.437]} />
      <mesh geometry={nodes.middlewall.geometry} material={materials.Walls} position={[-0.942, 1, -1.9]} />
      <mesh geometry={nodes.mediumcabinet.geometry} material={materials.Cabinet} position={[1.221, 1.595, 2.842]} />
      <mesh geometry={nodes.medcabhandle2.geometry} material={nodes.medcabhandle2.material} position={[2.899, 1.263, 3.358]} />
      <mesh geometry={nodes.medcabhandle.geometry} material={nodes.medcabhandle.material} position={[2.826, 1.263, 3.358]} />
      <mesh geometry={nodes.longcabinet001.geometry} material={materials.Cabinet} position={[-0.293, 1.595, 2.843]} />
      <mesh geometry={nodes.longcabinet.geometry} material={materials.Cabinet} position={[0.622, 1.595, 2.843]} />
      <mesh geometry={nodes.longcabhandle2003.geometry} material={nodes.longcabhandle2003.material} position={[3.265, 0.052, 3.144]} />
      <mesh geometry={nodes.longcabhandle2002.geometry} material={nodes.longcabhandle2002.material} position={[1.078, 0.052, 3.144]} />
      <mesh geometry={nodes.longcabhandle2001.geometry} material={nodes.longcabhandle2001.material} position={[1.138, 1.379, 3.358]} />
      <mesh geometry={nodes.longcabhandle2.geometry} material={nodes.longcabhandle2.material} position={[2.123, 1.379, 3.358]} />
      <mesh geometry={nodes.longcabhandle003.geometry} material={nodes.longcabhandle003.material} position={[3.203, 0.052, 3.144]} />
      <mesh geometry={nodes.longcabhandle002.geometry} material={nodes.longcabhandle002.material} position={[1.017, 0.052, 3.144]} />
      <mesh geometry={nodes.longcabhandle001.geometry} material={nodes.longcabhandle001.material} position={[1.076, 1.379, 3.358]} />
      <mesh geometry={nodes.longcabhandle.geometry} material={nodes.longcabhandle.material} position={[2.062, 1.379, 3.358]} />
      <mesh geometry={nodes.leftwall.geometry} material={materials.Walls} position={[-4.222, 1, -2.007]} />
      <mesh geometry={nodes.leftentrywall001.geometry} material={materials.Walls} position={[4.052, 1, 1.273]} />
      <mesh geometry={nodes.leftentrywall.geometry} material={materials.Walls} position={[-2.417, 1, 1.371]} />
      <mesh geometry={nodes.kitchenwall.geometry} material={materials.Walls} position={[-0.927, 1, 1.345]} />
      <mesh geometry={nodes.kitchenSink.geometry} material={nodes.kitchenSink.material} position={[1.908, 0.83, 2.878]} rotation={[0.22, 1.458, -0.212]} scale={[0.024, 0.027, 0.024]} />
      <mesh geometry={nodes.kitchensink.geometry} material={materials['Material.001']} position={[1.932, 0.828, 2.593]} rotation={[Math.PI, -1.568, Math.PI]} scale={0.3} />
      <mesh geometry={nodes.frontwall2.geometry} material={materials.Walls} position={[-3.256, 1, 3.908]} rotation={[-Math.PI, 1.565, -Math.PI]} />
      <mesh geometry={nodes.frontwall002.geometry} material={materials.Walls} position={[1.553, 1, -0.87]} rotation={[0, 1.571, 0]} />
      <mesh geometry={nodes.frontwall001.geometry} material={materials.Walls} position={[1.456, 1, 3.9]} rotation={[0, 1.571, 0]} />
      <mesh geometry={nodes.frontwall.geometry} material={materials.Walls} position={[-2.22, 1, 3.894]} rotation={[0, 1.571, 0]} />
      <mesh geometry={nodes.floor.geometry} material={materials.Floors} />
      <mesh geometry={nodes.entrywall.geometry} material={materials.Walls} position={[-1.672, 1, 2.106]} rotation={[-Math.PI, 1.565, -Math.PI]} />
      <mesh geometry={nodes.crwall001.geometry} material={materials.Walls} position={[4.053, 1, -0.338]} />
      <mesh geometry={nodes.crwall.geometry} material={materials.Walls} position={[-2.417, 1, -0.436]} />
      <mesh geometry={nodes.crsink002.geometry} material={nodes.crsink002.material} position={[6.334, 0.719, 1.684]} rotation={[0, 0.003, 0]} scale={[0.051, 0.067, 0.294]} />
      <mesh geometry={nodes.crsink001.geometry} material={nodes.crsink001.material} position={[-2.963, 0.719, 1.683]} rotation={[Math.PI, 0, Math.PI]} scale={[0.051, 0.067, 0.294]} />
      <mesh geometry={nodes.brwall001.geometry} material={materials.Walls} position={[5.512, 1, 1.527]} rotation={[-Math.PI, 1.565, -Math.PI]} />
      <mesh geometry={nodes.brwall.geometry} material={materials.Walls} position={[-3.39, 1, 1.436]} rotation={[-Math.PI, 1.565, -Math.PI]} />
      <mesh geometry={nodes.backwall.geometry} material={materials.Walls} position={[-2.226, 1, -2.008]} rotation={[0, 1.571, 0]} />
      <mesh geometry={nodes.sliding_door001.geometry} material={materials.Walls} position={[3.264, 0.654, -2.66]} rotation={[0, -1.57, 0]} />
      <mesh geometry={nodes.sliding_door.geometry} material={materials.Walls} position={[5.721, 0.654, -0.959]} rotation={[0, 1.568, 0]} />
      <mesh geometry={nodes.Cube002.geometry} material={nodes.Cube002.material} position={[5.143, 0.917, -1.767]} rotation={[0, 1.568, -3.137]} scale={-0.061} />
      <mesh geometry={nodes.Cube001.geometry} material={nodes.Cube001.material} position={[5.143, 0.831, -1.852]} rotation={[0, 1.568, 0]} scale={-0.061} />
      <mesh geometry={nodes.Cube.geometry} material={nodes.Cube.material} position={[5.003, 0.831, -1.798]} rotation={[0, 1.568, 0]} scale={-0.061} />
      <mesh geometry={nodes.sliding_door002.geometry} material={materials.Walls} position={[4.018, 0.654, -2.66]} rotation={[0, -1.57, 0]} />
      <mesh geometry={nodes.smallwall.geometry} material={materials.Walls} position={[4.84, 1.013, -1.563]} rotation={[0, -Math.PI / 2, 0]} />
      <mesh geometry={nodes.Plane001.geometry} material={materials.Floors} position={[4.546, 0.018, -2.991]} rotation={[0, -Math.PI / 2, 0]} />
      <mesh geometry={nodes.fence025.geometry} material={nodes.fence025.material} position={[5.688, 0.961, -2.339]} rotation={[1.562, 0.09, 0.001]} scale={0.024} />
      <mesh geometry={nodes.fence024.geometry} material={nodes.fence024.material} position={[3.758, 0.965, -2.96]} rotation={[1.571, 0.012, 1.571]} scale={[0.024, 0.027, 0.024]} />
      <mesh geometry={nodes.fence018.geometry} material={nodes.fence018.material} position={[5.745, 0.163, -2.717]} rotation={[0, -Math.PI / 2, 0]} scale={[0.058, 0.036, 0.088]} />
      <mesh geometry={nodes.fence017.geometry} material={nodes.fence017.material} position={[5.682, 0.967, -2.96]} rotation={[0, -Math.PI / 2, 0]} scale={-0.032} />
      <mesh geometry={nodes.fence010.geometry} material={nodes.fence010.material} position={[3.936, 0.163, -2.9]} rotation={[-Math.PI, 0.002, -Math.PI]} scale={[0.058, 0.036, 0.088]} />
      <mesh geometry={nodes.fence004.geometry} material={nodes.fence004.material} position={[5.731, 0.163, -2.905]} rotation={[-Math.PI, 0.002, -Math.PI]} scale={[0.058, 0.036, 0.088]} />
      <mesh geometry={nodes.fence003.geometry} material={nodes.fence003.material} position={[5.25, 0.163, -2.91]} rotation={[-Math.PI, 0.002, -Math.PI]} scale={[0.058, 0.036, 0.088]} />
      <mesh geometry={nodes.fence002.geometry} material={nodes.fence002.material} position={[4.8, 0.163, -2.905]} rotation={[-Math.PI, 0.002, -Math.PI]} scale={[0.058, 0.036, 0.088]} />
      <mesh geometry={nodes.fence001.geometry} material={nodes.fence001.material} position={[4.383, 0.163, -2.91]} rotation={[-Math.PI, 0.002, -Math.PI]} scale={[0.058, 0.036, 0.088]} />
      <mesh geometry={nodes.Text.geometry} material={materials.Floors} position={[-0.367, 0.127, 3.098]} rotation={[Math.PI / 2, 0, 0]} scale={0.492} />
      <mesh geometry={nodes.Text001.geometry} material={materials.Floors} position={[6.699, 0.091, 2.952]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={0.449} />
      <mesh geometry={nodes.Text002.geometry} material={materials.Floors} position={[3.317, 0.104, -3.007]} rotation={[Math.PI / 2, 0, Math.PI]} scale={0.434} />
      <mesh geometry={nodes.Text003.geometry} material={materials.Floors} position={[-3.339, 0.129, -2.973]} rotation={[Math.PI / 2, 0, Math.PI / 2]} scale={0.433} />
    </group>
  )
}

useGLTF.preload('/2brBig.glb')
