/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.15 studio.glb 
*/

import React, { useRef } from 'react';
import { useGLTF } from '@react-three/drei';

export default function UnitStudio(props) {
	const { nodes, materials } = useGLTF('/studio.glb');
	return (
		<group
			{...props}
			dispose={null}
		>
			<mesh
				geometry={nodes.floor.geometry}
				material={materials.Material}
				position={[-3.556, 1.004, 3.28]}
			/>
			<mesh
				geometry={nodes.frontwall.geometry}
				material={materials.E8E6D3}
				position={[3.389, 1.01, 1.299]}
			/>
			<mesh
				geometry={nodes.showerWall.geometry}
				material={materials['E8E6D3.001']}
				position={[3.391, 1.011, 2.115]}
			/>
			<mesh
				geometry={nodes.crWall.geometry}
				material={materials['E8E6D3.001']}
				position={[0.733, 0.647, 1.304]}
			/>
			<mesh
				geometry={nodes.crWall2.geometry}
				material={materials['E8E6D3.001']}
				position={[1.973, 1.005, 2.11]}
			/>
			<mesh
				geometry={nodes.showerGlass.geometry}
				material={materials['E8E6D3.001']}
				position={[2.5, 1.015, 0.822]}
			/>
			<mesh
				geometry={nodes.crGlass.geometry}
				material={materials['E8E6D3.001']}
				position={[1.543, 0.985, 0.827]}
			/>
			<mesh
				geometry={nodes.sinktable.geometry}
				material={materials['Material.005']}
				position={[2.882, 0.474, 1.187]}
			/>
			<mesh
				geometry={nodes.sinkCabinet.geometry}
				material={materials['Material.004']}
				position={[2.963, 0.333, 1.192]}
			/>
			<mesh
				geometry={nodes.sinkcabHandle.geometry}
				material={nodes.sinkcabHandle.material}
				position={[3.512, 0.285, 1.595]}
			/>
			<mesh
				geometry={nodes.sinkcabHandle2.geometry}
				material={nodes.sinkcabHandle2.material}
				position={[3.588, 0.283, 1.595]}
			/>
			<mesh
				geometry={nodes.tallCabinet.geometry}
				material={materials['987859']}
				position={[3.82, 0.416, 3.24]}
			/>
			<mesh
				geometry={nodes.sinktable001.geometry}
				material={materials['Material.003']}
				position={[2.296, 0.416, 3.243]}
			/>
			<mesh
				geometry={nodes.tallcabHandle.geometry}
				material={nodes.tallcabHandle.material}
				position={[4.495, 0.838, 3.562]}
			/>
			<mesh
				geometry={nodes.tallcabHandle2.geometry}
				material={nodes.tallcabHandle2.material}
				position={[4.578, 0.84, 3.563]}
			/>
			<mesh
				geometry={nodes.smallCabinet.geometry}
				material={materials['987859']}
				position={[2.291, 1.616, 3.243]}
			/>
			<mesh
				geometry={nodes.mediumcabinet.geometry}
				material={materials['987859']}
				position={[1.705, 1.615, 3.243]}
			/>
			<mesh
				geometry={nodes.longcabinet.geometry}
				material={materials['987859']}
				position={[1.106, 1.614, 3.243]}
			/>
			<mesh
				geometry={nodes.kitchenwall.geometry}
				material={materials['E8E6D3.001']}
				position={[0.725, 0.647, 2.887]}
			/>
			<mesh
				geometry={nodes.frontwall2.geometry}
				material={materials['E8E6D3.001']}
				position={[3.389, 1.01, 3.281]}
			/>
			<mesh
				geometry={nodes.backwall.geometry}
				material={materials['E8E6D3.001']}
				position={[-2.804, 0.647, 1.304]}
			/>
			<mesh
				geometry={nodes.smallwall.geometry}
				material={nodes.smallwall.material}
				position={[-1.837, 1.005, 2.003]}
			/>
			<mesh
				geometry={nodes.smallcabhandle.geometry}
				material={nodes.smallcabhandle.material}
				position={[3.897, 1.398, 3.759]}
			/>
			<mesh
				geometry={nodes.smallcabhandle2.geometry}
				material={nodes.smallcabhandle2.material}
				position={[3.946, 1.398, 3.759]}
			/>
			<mesh
				geometry={nodes.medcabhandle.geometry}
				material={nodes.medcabhandle.material}
				position={[3.31, 1.282, 3.759]}
			/>
			<mesh
				geometry={nodes.medcabhandle2.geometry}
				material={nodes.medcabhandle2.material}
				position={[3.383, 1.282, 3.759]}
			/>
			<mesh
				geometry={nodes.longcabhandle.geometry}
				material={nodes.longcabhandle.material}
				position={[2.546, 1.398, 3.759]}
			/>
			<mesh
				geometry={nodes.longcabhandle2.geometry}
				material={nodes.longcabhandle2.material}
				position={[2.607, 1.398, 3.759]}
			/>
			<mesh
				geometry={nodes.kitchensink.geometry}
				material={materials['Material.001']}
				position={[3.431, 0.814, 2.999]}
				rotation={[Math.PI, -1.568, Math.PI]}
				scale={0.3}
			/>
			<mesh
				geometry={nodes.Circle.geometry}
				material={nodes.Circle.material}
				position={[3.407, 0.816, 3.283]}
				rotation={[0.22, 1.458, -0.212]}
				scale={[0.024, 0.027, 0.024]}
			/>
			<mesh
				geometry={nodes.sinkHandle.geometry}
				material={nodes.sinkHandle.material}
				position={[3.479, 0.813, 3.283]}
				scale={0.015}
			/>
			<mesh
				geometry={nodes.sinkhandle2.geometry}
				material={nodes.sinkhandle2.material}
				position={[3.339, 0.815, 3.283]}
				scale={0.015}
			/>
			<mesh
				geometry={nodes.crsink.geometry}
				material={nodes.crsink.material}
				position={[3.006, 0.689, 0.554]}
				rotation={[-Math.PI, 1.569, -Math.PI]}
				scale={[0.051, 0.067, 0.294]}
			/>
			<mesh
				geometry={nodes.tap.geometry}
				material={nodes.tap.material}
				position={[3.008, 0.82, 0.352]}
				rotation={[0, 1.549, 0]}
				scale={[0.023, 0.065, 0.023]}
			/>
			<mesh
				geometry={nodes.taphandle.geometry}
				material={nodes.taphandle.material}
				position={[3.008, 0.821, 0.352]}
				rotation={[0, 1.549, 0]}
				scale={[0.023, 0.065, 0.023]}
			/>
			<mesh
				geometry={nodes.leftwall.geometry}
				material={materials['E8E6D3.001']}
				position={[4.344, 0.991, 1.292]}
				rotation={[0, 1.562, 0]}
			/>
			<group
				position={[-1.277, 0.992, 1.149]}
				rotation={[-Math.PI, 0.007, -Math.PI]}
			>
				<mesh
					geometry={nodes.Cube036.geometry}
					material={materials['E8E6D3.001']}
				/>
				<mesh
					geometry={nodes.Cube036_1.geometry}
					material={materials.window}
				/>
			</group>
			<mesh
				geometry={nodes.righwall.geometry}
				material={materials.E8E6D3}
				position={[4.355, 0.992, 4.297]}
				rotation={[0, 1.562, 0]}
			/>
			<mesh
				geometry={nodes.showrebase.geometry}
				material={materials['Material.008']}
				position={[3.898, 1.737, 0.32]}
				rotation={[3.142, 1.569, -1.57]}
				scale={0.075}
			/>
			<mesh
				geometry={nodes.shower.geometry}
				material={materials['Material.007']}
				position={[3.898, 1.737, 0.344]}
				rotation={[-Math.PI, 1.569, -Math.PI]}
				scale={0.021}
			/>
			<mesh
				geometry={nodes.showerbody.geometry}
				material={nodes.showerbody.material}
				position={[3.899, 1.7, 0.767]}
				rotation={[-Math.PI, 1.569, -Math.PI]}
				scale={0.015}
			/>
			<mesh
				geometry={nodes.showerhead.geometry}
				material={materials['Material.006']}
				position={[3.899, 1.677, 0.772]}
				rotation={[-Math.PI, 1.569, -0.003]}
				scale={0.075}
			/>
			<mesh
				geometry={nodes.toilet.geometry}
				material={nodes.toilet.material}
				position={[2.099, 0.27, 0.548]}
				rotation={[0, -1.566, 0]}
				scale={0.223}
			/>
			<mesh
				geometry={nodes.Text002.geometry}
				material={nodes.Text002.material}
				position={[-2.276, 0.102, 0.342]}
				rotation={[1.575, 0.01, 1.574]}
				scale={0.382}
			/>
			<mesh
				geometry={nodes.Text.geometry}
				material={materials.Material}
				position={[-2.195, 0.132, 3.309]}
				rotation={[Math.PI / 2, 0, 0]}
				scale={0.431}
			/>
			<mesh
				geometry={nodes.Text001.geometry}
				material={materials.Material}
				position={[4.323, 0.132, 0.297]}
				rotation={[Math.PI / 2, 0, 3.141]}
				scale={0.431}
			/>
		</group>
	);
}

useGLTF.preload('/studio.glb');
