/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.15 3br.glb 
*/

import React, { useRef } from 'react';
import { useGLTF } from '@react-three/drei';

export default function Unit3br(props) {
	const { nodes, materials } = useGLTF('/3br.glb');
	return (
		<group
			{...props}
			dispose={null}
		>
			<group
				position={[-3.638, 0.987, -3.465]}
				rotation={[-Math.PI, 0.011, -Math.PI]}
			>
				<mesh
					geometry={nodes.Cube051.geometry}
					material={materials['Material.002']}
				/>
				<mesh
					geometry={nodes.Cube051_1.geometry}
					material={materials['window.001']}
				/>
				<lineSegments
					geometry={nodes.Cube051_2.geometry}
					material={materials['Material.002']}
				/>
			</group>
			<group
				position={[-2.646, 0.987, 0.617]}
				rotation={[-Math.PI, 0.011, -Math.PI]}
			>
				<mesh
					geometry={nodes.Cube050.geometry}
					material={materials['Material.003']}
				/>
				<mesh
					geometry={nodes.Cube050_1.geometry}
					material={materials.window}
				/>
				<lineSegments
					geometry={nodes.Cube050_2.geometry}
					material={materials['Material.003']}
				/>
			</group>
			<mesh
				geometry={nodes.toilet.geometry}
				material={nodes.toilet.material}
				position={[-2.639, 0.269, -1.148]}
				rotation={[0, -1.568, 0]}
				scale={0.223}
			/>
			<mesh
				geometry={nodes.taphandle001.geometry}
				material={nodes.taphandle001.material}
				position={[-1.665, 0.851, -1.332]}
				rotation={[0, 1.548, 0]}
				scale={[0.023, 0.065, 0.023]}
			/>
			<mesh
				geometry={nodes.tap001.geometry}
				material={nodes.tap001.material}
				position={[-1.665, 0.85, -1.332]}
				rotation={[0, 1.548, 0]}
				scale={[0.023, 0.065, 0.023]}
			/>
			<mesh
				geometry={nodes.smallCabinet.geometry}
				material={materials['987859']}
				position={[1.83, 1.596, -3.949]}
				rotation={[-3.138, -0.005, -3.139]}
			/>
			<mesh
				geometry={nodes.smallcabhandle2.geometry}
				material={nodes.smallcabhandle2.material}
				position={[0.172, 1.409, -4.462]}
				rotation={[-3.112, -0.005, -3.139]}
			/>
			<mesh
				geometry={nodes.smallcabhandle.geometry}
				material={nodes.smallcabhandle.material}
				position={[0.221, 1.409, -4.462]}
				rotation={[-3.112, -0.005, -3.139]}
			/>
			<mesh
				geometry={nodes.sinktable005.geometry}
				material={materials.AFB1AE}
				position={[2.853, 0.43, -3.924]}
				rotation={[Math.PI, -0.004, Math.PI]}
			/>
			<mesh
				geometry={nodes.sinktable004.geometry}
				material={materials.AAAAAA}
				position={[-1.793, 0.504, -0.497]}
				rotation={[0, -0.001, 0]}
			/>
			<mesh
				geometry={nodes.sinktable003.geometry}
				material={materials.AFB1AE}
				position={[1.893, 0.43, -3.925]}
				rotation={[Math.PI, -0.004, Math.PI]}
			/>
			<mesh
				geometry={nodes.sinktable002.geometry}
				material={materials.AFB1AE}
				position={[0.159, 0.43, -4.224]}
				rotation={[Math.PI, -1.57, Math.PI]}
			/>
			<mesh
				geometry={nodes.sinktable001.geometry}
				material={materials.AFB1AE}
				position={[0.158, 0.43, -3.285]}
				rotation={[Math.PI, -1.57, Math.PI]}
			/>
			<mesh
				geometry={nodes.sinkhandle2.geometry}
				material={nodes.sinkhandle2.material}
				position={[0.118, 0.829, -2.243]}
				rotation={[Math.PI, -1.57, Math.PI]}
				scale={0.015}
			/>
			<mesh
				geometry={nodes.sinkHandle.geometry}
				material={nodes.sinkHandle.material}
				position={[0.118, 0.827, -2.103]}
				rotation={[Math.PI, -1.57, Math.PI]}
				scale={0.015}
			/>
			<mesh
				geometry={nodes.sinkCabinet001.geometry}
				material={materials.AFB1AE}
				position={[-1.711, 0.363, -0.492]}
				rotation={[0, -0.001, 0]}
			/>
			<mesh
				geometry={nodes.sinkcabHandle2001.geometry}
				material={nodes.sinkcabHandle2001.material}
				position={[-1.087, 0.313, -0.088]}
				rotation={[0, -0.001, 0]}
			/>
			<mesh
				geometry={nodes.sinkcabHandle001.geometry}
				material={nodes.sinkcabHandle001.material}
				position={[-1.163, 0.315, -0.088]}
				rotation={[0, -0.001, 0]}
			/>
			<mesh
				geometry={nodes.showrebase.geometry}
				material={materials.AAAAAA}
				position={[-3.838, 1.746, -1.354]}
				rotation={[0, 1.569, 1.572]}
				scale={0.075}
			/>
			<mesh
				geometry={nodes.showerhead.geometry}
				material={materials.AAAAAA}
				position={[-3.839, 1.686, -0.902]}
				rotation={[0, 1.569, 3.139]}
				scale={0.075}
			/>
			<mesh
				geometry={nodes.showerGlass.geometry}
				material={materials.E8E6D3}
				position={[-4.224, 1.014, -0.411]}
				rotation={[0, -0.013, 0]}
			/>
			<mesh
				geometry={nodes.showerbody.geometry}
				material={nodes.showerbody.material}
				position={[-3.839, 1.709, -0.907]}
				rotation={[0, 1.569, 0]}
				scale={0.015}
			/>
			<mesh
				geometry={nodes.shower.geometry}
				material={materials.AAAAAA}
				position={[-3.839, 1.746, -1.33]}
				rotation={[0, 1.569, 0]}
				scale={0.021}
			/>
			<mesh
				geometry={nodes.salawall.geometry}
				material={materials.E8E6D3}
				position={[-0.901, 1.014, -3.043]}
				rotation={[-Math.PI, 1.564, -Math.PI]}
			/>
			<mesh
				geometry={nodes.rightwall.geometry}
				material={materials.E8E6D3}
				position={[2.789, 1.015, -4.935]}
			/>
			<mesh
				geometry={nodes.mediumcabinet.geometry}
				material={materials['987859']}
				position={[2.416, 1.605, -3.952]}
				rotation={[-3.129, -0.005, -3.139]}
			/>
			<mesh
				geometry={nodes.medcabhandle2.geometry}
				material={nodes.medcabhandle2.material}
				position={[0.734, 1.291, -4.468]}
				rotation={[-3.112, -0.005, -3.139]}
			/>
			<mesh
				geometry={nodes.medcabhandle.geometry}
				material={nodes.medcabhandle.material}
				position={[0.807, 1.291, -4.469]}
				rotation={[-3.112, -0.005, -3.139]}
			/>
			<mesh
				geometry={nodes.longcabinet002.geometry}
				material={materials['987859']}
				position={[0.164, 1.598, -3.27]}
				rotation={[Math.PI, -1.57, Math.PI]}
			/>
			<mesh
				geometry={nodes.longcabinet001.geometry}
				material={materials['987859']}
				position={[0.165, 1.605, -4.185]}
				rotation={[Math.PI, -1.57, Math.PI]}
			/>
			<mesh
				geometry={nodes.longcabinet.geometry}
				material={materials['987859']}
				position={[3.015, 1.603, -3.956]}
				rotation={[-3.129, -0.005, -3.139]}
			/>
			<mesh
				geometry={nodes.longcabhandle2004.geometry}
				material={nodes.longcabhandle2004.material}
				position={[-0.352, 1.383, -1.769]}
				rotation={[Math.PI, -1.57, Math.PI]}
			/>
			<mesh
				geometry={nodes.longcabhandle2003.geometry}
				material={nodes.longcabhandle2003.material}
				position={[-0.351, 1.383, -2.755]}
				rotation={[Math.PI, -1.57, Math.PI]}
			/>
			<mesh
				geometry={nodes.longcabhandle2002.geometry}
				material={nodes.longcabhandle2002.material}
				position={[0.646, 0.052, -4.234]}
				rotation={[Math.PI, -0.004, Math.PI]}
			/>
			<mesh
				geometry={nodes.longcabhandle2001.geometry}
				material={nodes.longcabhandle2001.material}
				position={[1.606, 0.052, -4.234]}
				rotation={[Math.PI, -0.004, Math.PI]}
			/>
			<mesh
				geometry={nodes.longcabhandle2.geometry}
				material={nodes.longcabhandle2.material}
				position={[1.51, 1.406, -4.469]}
				rotation={[-3.112, -0.005, -3.139]}
			/>
			<mesh
				geometry={nodes.longcabhandle004.geometry}
				material={nodes.longcabhandle004.material}
				position={[-0.352, 1.383, -1.83]}
				rotation={[Math.PI, -1.57, Math.PI]}
			/>
			<mesh
				geometry={nodes.longcabhandle003.geometry}
				material={nodes.longcabhandle003.material}
				position={[-0.351, 1.383, -2.816]}
				rotation={[Math.PI, -1.57, Math.PI]}
			/>
			<mesh
				geometry={nodes.longcabhandle002.geometry}
				material={nodes.longcabhandle002.material}
				position={[0.707, 0.052, -4.235]}
				rotation={[Math.PI, -0.004, Math.PI]}
			/>
			<mesh
				geometry={nodes.longcabhandle001.geometry}
				material={nodes.longcabhandle001.material}
				position={[1.667, 0.052, -4.234]}
				rotation={[Math.PI, -0.004, Math.PI]}
			/>
			<mesh
				geometry={nodes.longcabhandle.geometry}
				material={nodes.longcabhandle.material}
				position={[1.571, 1.406, -4.469]}
				rotation={[-3.112, -0.005, -3.139]}
			/>
			<mesh
				geometry={nodes.leftwall.geometry}
				material={materials.E8E6D3}
				position={[2.789, 1.015, 2.437]}
			/>
			<mesh
				geometry={nodes.leftcrwall.geometry}
				material={materials.E8E6D3}
				position={[1.772, 1.023, -2.38]}
			/>
			<mesh
				geometry={nodes.kitchensink.geometry}
				material={materials['Material.001']}
				position={[0.402, 0.828, -2.151]}
				rotation={[-Math.PI, 0.003, -Math.PI]}
				scale={0.3}
			/>
			<mesh
				geometry={nodes.kitchenSink.geometry}
				material={nodes.kitchenSink.material}
				position={[0.117, 0.83, -2.175]}
				rotation={[0.025, -0.111, 0.01]}
				scale={[0.024, 0.027, 0.024]}
			/>
			<mesh
				geometry={nodes.frontwall.geometry}
				material={materials.E8E6D3}
				position={[2.803, 1.014, -3.043]}
				rotation={[-Math.PI, 1.564, -Math.PI]}
			/>
			<mesh
				geometry={nodes.floor.geometry}
				material={materials['271F1F']}
			/>
			<mesh
				geometry={nodes.crsink001.geometry}
				material={nodes.crsink001.material}
				position={[-1.668, 0.719, -1.13]}
				rotation={[0, 1.571, 0]}
				scale={[0.051, 0.067, 0.294]}
			/>
			<mesh
				geometry={nodes.crleftwall.geometry}
				material={materials.E8E6D3}
				position={[1.795, 1.006, -0.648]}
			/>
			<mesh
				geometry={nodes.crentrywall.geometry}
				material={materials.E8E6D3}
				position={[-1.994, 1.014, -2.988]}
				rotation={[-Math.PI, 1.564, -Math.PI]}
			/>
			<mesh
				geometry={nodes.backwall.geometry}
				material={materials.E8E6D3}
				position={[-5.611, 1.014, -0.487]}
				rotation={[-Math.PI, 1.564, -Math.PI]}
			/>
			<mesh
				geometry={nodes.backfloor.geometry}
				material={materials['271F1F']}
				position={[-3.623, 0, -2.22]}
			/>
			<mesh
				geometry={nodes.b2wall.geometry}
				material={materials.E8E6D3}
				position={[-0.901, 1.014, 1.678]}
				rotation={[-Math.PI, 1.564, -Math.PI]}
			/>
			<mesh
				geometry={nodes.b2mwall.geometry}
				material={materials.E8E6D3}
				position={[-4.6, 1.014, 0.585]}
				rotation={[0, 1.567, 0]}
			/>
			<mesh
				geometry={nodes.b1wall.geometry}
				material={materials.E8E6D3}
				position={[-5.618, 1.014, -3.043]}
				rotation={[-Math.PI, 1.569, -Math.PI]}
			/>
			<mesh
				geometry={nodes.b2swall001.geometry}
				material={materials.E8E6D3}
				position={[1.764, 1.006, -4.286]}
			/>
			<mesh
				geometry={nodes.b2mwall001.geometry}
				material={materials.E8E6D3}
				position={[-4.695, 1.014, -6.135]}
				rotation={[0, 1.567, 0]}
			/>
			<mesh
				geometry={nodes.b2mwall002.geometry}
				material={materials.E8E6D3}
				position={[-1.763, 1.014, 1.338]}
				rotation={[0, 1.567, 0]}
			/>
			<mesh
				geometry={nodes.b2swall002.geometry}
				material={materials.E8E6D3}
				position={[2.878, 1.006, 2.442]}
			/>
			<mesh
				geometry={nodes.balconyfloor.geometry}
				material={materials.Material}
				position={[-1.794, 0.008, 3.631]}
			/>
			<mesh
				geometry={nodes.fence.geometry}
				material={nodes.fence.material}
				position={[-0.883, 0.163, 4.558]}
				scale={[0.058, 0.036, 0.088]}
			/>
			<mesh
				geometry={nodes.fence2.geometry}
				material={nodes.fence2.material}
				position={[0.865, 0.163, 4.558]}
				scale={[0.058, 0.036, 0.088]}
			/>
			<mesh
				geometry={nodes.fence001.geometry}
				material={nodes.fence001.material}
				position={[-0.883, 0.163, 4.558]}
				scale={[0.058, 0.036, 0.088]}
			/>
			<mesh
				geometry={nodes.fence002.geometry}
				material={nodes.fence002.material}
				position={[-1.494, 0.163, 4.558]}
				scale={[0.058, 0.036, 0.088]}
			/>
			<mesh
				geometry={nodes.fence003.geometry}
				material={nodes.fence003.material}
				position={[-2.095, 0.163, 4.558]}
				scale={[0.058, 0.036, 0.088]}
			/>
			<mesh
				geometry={nodes.fence004.geometry}
				material={nodes.fence004.material}
				position={[-2.706, 0.163, 4.558]}
				scale={[0.058, 0.036, 0.088]}
			/>
			<mesh
				geometry={nodes.fence005.geometry}
				material={nodes.fence005.material}
				position={[-3.256, 0.163, 4.558]}
				scale={[0.058, 0.036, 0.088]}
			/>
			<mesh
				geometry={nodes.fence006.geometry}
				material={nodes.fence006.material}
				position={[-3.812, 0.163, 4.558]}
				scale={[0.058, 0.036, 0.088]}
			/>
			<mesh
				geometry={nodes.fence007.geometry}
				material={nodes.fence007.material}
				position={[-4.306, 0.163, 4.558]}
				scale={[0.058, 0.036, 0.088]}
			/>
			<mesh
				geometry={nodes.fence008.geometry}
				material={nodes.fence008.material}
				position={[-4.727, 0.163, 4.558]}
				scale={[0.058, 0.036, 0.088]}
			/>
			<mesh
				geometry={nodes.fence009.geometry}
				material={nodes.fence009.material}
				position={[-4.727, 0.163, 4.558]}
				scale={[0.058, 0.036, 0.088]}
			/>
			<mesh
				geometry={nodes.fence010.geometry}
				material={nodes.fence010.material}
				position={[-4.632, 0.163, 4.184]}
				rotation={[Math.PI, -1.569, Math.PI]}
				scale={[0.058, 0.036, 0.088]}
			/>
			<mesh
				geometry={nodes.fence011.geometry}
				material={nodes.fence011.material}
				position={[-4.632, 0.163, 3.695]}
				rotation={[Math.PI, -1.569, Math.PI]}
				scale={[0.058, 0.036, 0.088]}
			/>
			<mesh
				geometry={nodes.fence012.geometry}
				material={nodes.fence012.material}
				position={[-4.632, 0.163, 3.278]}
				rotation={[Math.PI, -1.569, Math.PI]}
				scale={[0.058, 0.036, 0.088]}
			/>
			<mesh
				geometry={nodes.fence013.geometry}
				material={nodes.fence013.material}
				position={[-4.632, 0.163, 2.731]}
				rotation={[Math.PI, -1.569, Math.PI]}
				scale={[0.058, 0.036, 0.088]}
			/>
			<mesh
				geometry={nodes.fence014.geometry}
				material={nodes.fence014.material}
				position={[-4.306, 0.163, 2.727]}
				scale={[0.058, 0.036, 0.088]}
			/>
			<mesh
				geometry={nodes.fence022.geometry}
				material={nodes.fence022.material}
				position={[-0.815, 0.965, 4.21]}
				rotation={[1.583, 0, 0]}
				scale={0.024}
			/>
			<mesh
				geometry={nodes.fence015.geometry}
				material={nodes.fence015.material}
				position={[-0.822, 0.967, 4.609]}
				scale={-0.032}
			/>
			<mesh
				geometry={nodes.fence023.geometry}
				material={nodes.fence023.material}
				position={[-1.219, 0.961, 4.608]}
				rotation={[1.661, 0.009, -1.571]}
				scale={0.024}
			/>
			<mesh
				geometry={nodes.fence016.geometry}
				material={nodes.fence016.material}
				position={[-4.678, 0.967, 4.609]}
				scale={-0.032}
			/>
			<mesh
				geometry={nodes.fence024.geometry}
				material={nodes.fence024.material}
				position={[-4.684, 0.965, 4.211]}
				rotation={[1.583, 0, 0]}
				scale={0.024}
			/>
			<mesh
				geometry={nodes.fence017.geometry}
				material={nodes.fence017.material}
				position={[-4.678, 0.967, 2.79]}
				scale={-0.032}
			/>
			<mesh
				geometry={nodes.fence025.geometry}
				material={nodes.fence025.material}
				position={[-4.082, 0.961, 2.784]}
				rotation={[1.661, 0.009, -1.571]}
				scale={0.024}
			/>
			<mesh
				geometry={nodes.b2swall003.geometry}
				material={materials.E8E6D3}
				position={[5.6, 1.006, 2.442]}
			/>
			<mesh
				geometry={nodes.b2mwall003.geometry}
				material={materials.E8E6D3}
				position={[0.021, 1.014, 1.338]}
				rotation={[0, 1.567, 0]}
			/>
			<mesh
				geometry={nodes.balconyfloor2.geometry}
				material={materials['Material.005']}
				position={[3.15, 0.008, 3.631]}
			/>
			<mesh
				geometry={nodes.b2mwall004.geometry}
				material={materials.E8E6D3}
				position={[2.236, 1.014, 1.348]}
				rotation={[0, 1.567, 0]}
			/>
			<mesh
				geometry={nodes.fence018.geometry}
				material={nodes.fence018.material}
				position={[1.417, 0.163, 4.558]}
				scale={[0.058, 0.036, 0.088]}
			/>
			<mesh
				geometry={nodes.fence019.geometry}
				material={nodes.fence019.material}
				position={[2.096, 0.163, 4.558]}
				scale={[0.058, 0.036, 0.088]}
			/>
			<mesh
				geometry={nodes.fence020.geometry}
				material={nodes.fence020.material}
				position={[2.659, 0.163, 4.558]}
				scale={[0.058, 0.036, 0.088]}
			/>
			<mesh
				geometry={nodes.fence026.geometry}
				material={nodes.fence026.material}
				position={[2.737, 0.961, 4.608]}
				rotation={[1.661, 0.009, -1.571]}
				scale={0.024}
			/>
			<mesh
				geometry={nodes.fence021.geometry}
				material={nodes.fence021.material}
				position={[0.932, 0.967, 4.609]}
				scale={-0.032}
			/>
			<mesh
				geometry={nodes.fence027.geometry}
				material={nodes.fence027.material}
				position={[0.928, 0.965, 4.21]}
				rotation={[1.583, 0, 0]}
				scale={0.024}
			/>
			<mesh
				geometry={nodes.leftwall001.geometry}
				material={materials.E8E6D3}
				position={[4.101, 1.015, 3.623]}
			/>
			<mesh
				geometry={nodes.frontwall001.geometry}
				material={materials.E8E6D3}
				position={[5.422, 1.014, -1.776]}
				rotation={[-Math.PI, 1.564, -Math.PI]}
			/>
			<mesh
				geometry={nodes.entrancewall001.geometry}
				material={materials.E8E6D3}
				position={[11.57, 1.006, -2.87]}
			/>
			<mesh
				geometry={nodes.leftentrancewall001.geometry}
				material={materials.E8E6D3}
				position={[2.799, 1.014, -5.624]}
				rotation={[-Math.PI, 1.564, -Math.PI]}
			/>
			<mesh
				geometry={nodes.b2mwall005.geometry}
				material={materials.E8E6D3}
				position={[2.236, 1.014, 1.348]}
				rotation={[0, 1.567, 0]}
			/>
			<mesh
				geometry={nodes.frontwall002.geometry}
				material={materials.E8E6D3}
				position={[2.803, 1.014, 0.156]}
				rotation={[-Math.PI, 1.564, -Math.PI]}
			/>
			<mesh
				geometry={nodes.floor001.geometry}
				material={materials['271F1F']}
				position={[4.738, 0, 1.551]}
				scale={[0.411, 0.673, 0.862]}
			/>
			<group
				position={[3.787, 0.987, 3.513]}
				rotation={[Math.PI, -1.559, Math.PI]}
			>
				<mesh
					geometry={nodes.Cube087.geometry}
					material={materials['Material.004']}
				/>
				<mesh
					geometry={nodes.Cube087_1.geometry}
					material={materials['window.002']}
				/>
				<lineSegments
					geometry={nodes.Cube087_2.geometry}
					material={materials['Material.004']}
				/>
			</group>
			<mesh
				geometry={nodes.Text.geometry}
				material={materials['000']}
				position={[3.285, 0.089, 4.671]}
				rotation={[Math.PI / 2, 0, 0]}
				scale={0.359}
			/>
			<mesh
				geometry={nodes.Text001.geometry}
				material={materials['000']}
				position={[6.459, 0.105, 4.573]}
				rotation={[Math.PI / 2, 0, -Math.PI / 2]}
				scale={0.332}
			/>
			<mesh
				geometry={nodes.Text002.geometry}
				material={materials['000']}
				position={[3.784, 0.139, -4.081]}
				rotation={[Math.PI / 2, 0, Math.PI]}
				scale={0.443}
			/>
			<mesh
				geometry={nodes.Text003.geometry}
				material={materials['000']}
				position={[-4.776, 0.116, -3.428]}
				rotation={[Math.PI / 2, 0, Math.PI / 2]}
				scale={0.284}
			/>
		</group>
	);
}

useGLTF.preload('/3br.glb');
