/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.12 living6.glb
*/

import React, { forwardRef } from 'react';
import { useGLTF } from '@react-three/drei';

const Living6 = forwardRef(({ events, props, action, rotate, color }, ref) => {
	const { nodes, materials } = useGLTF('/living6.glb');
  return (
    <group
			dispose={null}
			{...props}
			{...events}
			ref={ref}
			onClick={action}
			rotation-y={rotate}
		>
      <group position={[1.007, -17.103, -3.615]} rotation={[-Math.PI / 2, 0, 0]} scale={[18.862, 14.268, 18.862]}>
        <mesh geometry={nodes.bedside_table_Material033_0.geometry} material={materials['Material.033']} material-color={color.Box ? color.Box : null} />
        <mesh geometry={nodes.bedside_table_steel001_0.geometry} material={materials['steel.001']} material-color={color.Handle ? color.Handle : null} />
      </group>
    </group>
  )
});

useGLTF.preload('/living6.glb');

export default Living6 ;
