/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.12 living7.glb
*/

import React, { forwardRef } from 'react';
import { useGLTF } from '@react-three/drei';

const Living7 = forwardRef(({ events, props, action, rotate, color }, ref) => {
	const { nodes, materials } = useGLTF('/living7.glb');
  return (
    <group
			dispose={null}
			{...props}
			{...events}
			ref={ref}
			onClick={action}
			rotation-y={rotate}
		>
      <group position={[0, 0.365, 0]}>
        <group position={[-20.176, 89.446, -17.422]}>
          <mesh geometry={nodes.Stretto_Tall_Shelves_Grey_MEDIUM_GREY_0.geometry} material={materials.MEDIUM_GREY} material-color={color.Shelves ? color.Shelves : null} />
          <mesh geometry={nodes.Stretto_Tall_Shelves_Grey_WHITE_0.geometry} material={materials.WHITE} material-color={color.Panel ? color.Panel : null} />
        </group>
      </group>
    </group>
  )
});

useGLTF.preload('/living7.glb');

export default Living7 ;

