/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.12 living2.glb
*/

import React, { forwardRef } from 'react';
import { useGLTF } from '@react-three/drei';

const Living2 = forwardRef(({ events, props, action, rotate, color }, ref) => {
	const { nodes, materials } = useGLTF('/living2.glb');
  return (
    <group
			dispose={null}
			{...props}
			{...events}
			ref={ref}
			onClick={action}
			rotation-y={rotate}
		>
      <group position={[0, 0.073, 0]}>
        <mesh geometry={nodes.Object_8.geometry} material={materials.material_0} material-color={color.Wood ? color.Wood : null} />
        <mesh geometry={nodes.Object_6.geometry} material={materials.material_0} position={[0, 0.284, -0.048]} rotation={[-Math.PI, 0, 0]} scale={[0.988, 0.638, 0.978]} />
      </group>
      <mesh geometry={nodes.Object_10.geometry} material={materials.Standardmaterial} position={[-0.027, 0.013, -0.013]} rotation={[0, 0.995, 0]} scale={[0.021, 1.189, 0.008]} />
      <mesh geometry={nodes.Object_14.geometry} material={materials.Standardmaterial} position={[-0.239, 0, -0.194]} rotation={[0, 0.716, 0]} scale={[0.021, 1.206, 0.092]} />
      <mesh geometry={nodes.Object_12.geometry} material={materials.Standardmaterial} position={[0.21, 0, -0.157]} rotation={[0, -Math.PI / 3, 0]} scale={[0.021, 1.206, 0.092]} />
      <mesh geometry={nodes.Object_20.geometry} material={materials.Standardmaterial} position={[-0.027, 0.02, 0.247]} rotation={[-Math.PI / 2, 0, 0]} scale={[0.021, 1.306, 0.092]} />
      <mesh geometry={nodes.Object_18.geometry} material={materials.Standardmaterial} position={[-0.027, 0.02, -0.016]} rotation={[-Math.PI / 2, 0, 0.873]} scale={[0.021, 1.381, 0.092]} />
      <mesh geometry={nodes.Object_16.geometry} material={materials.Standardmaterial} position={[-0.027, 0.02, -0.016]} rotation={[-Math.PI / 2, 0, -1.03]} scale={[0.021, 1.381, 0.092]} />
      <mesh geometry={nodes.Object_22.geometry} material={materials.Standardmaterial} position={[-0.027, 0, 0.247]} scale={[0.021, 1.206, 0.092]} />
    </group>
  )
});

useGLTF.preload('/living2.glb');

export default Living2 ;
