/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.12 living8.glb
*/

import React, { forwardRef } from 'react';
import { useGLTF } from '@react-three/drei';

const Living8 = forwardRef(({ events, props, action, rotate, color }, ref) => {
	const { nodes, materials } = useGLTF('/living8.glb');
  return (
    <group
    dispose={null}
    {...props}
    {...events}
    ref={ref}
    onClick={action}
    rotation-y={rotate}
  >
      <group position={[2.627, 3.915, 0.102]} scale={0.268}>
        <mesh geometry={nodes.Object_46.geometry} material={materials['.008']} />
        <mesh geometry={nodes.Object_47.geometry} material={materials['.009']} />
      </group>
      <group position={[9.724, 3.915, 0.102]} scale={0.268}>
        <mesh geometry={nodes.Object_49.geometry} material={materials['.008']} />
        <mesh geometry={nodes.Object_50.geometry} material={materials['.009']} />
      </group>
      <group position={[2.627, 9.036, 0.102]} scale={0.268}>
        <mesh geometry={nodes.Object_52.geometry} material={materials['.008']} />
        <mesh geometry={nodes.Object_53.geometry} material={materials['.009']} />
      </group>
      <group position={[9.724, 9.036, 0.102]} scale={0.268}>
        <mesh geometry={nodes.Object_55.geometry} material={materials['.008']} />
        <mesh geometry={nodes.Object_56.geometry} material={materials['.009']} />
      </group>
      <group position={[2.627, 14.19, 0.102]} scale={0.268}>
        <mesh geometry={nodes.Object_58.geometry} material={materials['.008']} />
        <mesh geometry={nodes.Object_59.geometry} material={materials['.009']} />
      </group>
      <group position={[9.724, 14.19, 0.102]} scale={0.268}>
        <mesh geometry={nodes.Object_61.geometry} material={materials['.008']} />
        <mesh geometry={nodes.Object_62.geometry} material={materials['.009']} />
      </group>
      <group position={[1.335, 6.49, 0.102]} scale={0.268}>
        <mesh geometry={nodes.Object_64.geometry} material={materials['.008']} />
        <mesh geometry={nodes.Object_65.geometry} material={materials['.009']} />
      </group>
      <group position={[6.203, 6.49, 0.102]} scale={0.268}>
        <mesh geometry={nodes.Object_67.geometry} material={materials['.008']} />
        <mesh geometry={nodes.Object_68.geometry} material={materials['.009']} />
      </group>
      <group position={[10.952, 6.49, 0.102]} scale={0.268}>
        <mesh geometry={nodes.Object_70.geometry} material={materials['.008']} />
        <mesh geometry={nodes.Object_71.geometry} material={materials['.009']} />
      </group>
      <group position={[1.335, 11.622, 0.102]} scale={0.268}>
        <mesh geometry={nodes.Object_73.geometry} material={materials['.008']} />
        <mesh geometry={nodes.Object_74.geometry} material={materials['.009']} />
      </group>
      <group position={[6.203, 11.622, 0.102]} scale={0.268}>
        <mesh geometry={nodes.Object_76.geometry} material={materials['.008']} />
        <mesh geometry={nodes.Object_77.geometry} material={materials['.009']} />
      </group>
      <group position={[10.952, 11.622, 0.102]} scale={0.268}>
        <mesh geometry={nodes.Object_79.geometry} material={materials['.008']} />
        <mesh geometry={nodes.Object_80.geometry} material={materials['.009']} />
      </group>
      <mesh geometry={nodes.Object_6.geometry} material={materials['.003']} position={[-0.88, 13.86, 0]} rotation={[0, 0, -Math.PI / 2]} scale={[1, 0.111, 1]} material-color={color.Shelves ? color.Shelves : null} />
      <mesh geometry={nodes.Object_8.geometry} material={materials['.003']} position={[13.316, 13.86, 0]} rotation={[0, 0, -Math.PI / 2]} scale={[1, 0.111, 1]} material-color={color.Shelves ? color.Shelves : null} />
      <mesh geometry={nodes.Object_10.geometry} material={materials['.003']} position={[0, 14.405, 0]} scale={[1, 0.111, 1]} material-color={color.Shelves ? color.Shelves : null}/>
      <mesh geometry={nodes.Object_12.geometry} material={materials['.003']} position={[0, 11.832, 0]} scale={[1, 0.111, 1]} material-color={color.Shelves ? color.Shelves : null}/>
      <mesh geometry={nodes.Object_14.geometry} material={materials['.003']} position={[0, 9.253, 0]} scale={[1, 0.111, 1]} material-color={color.Shelves ? color.Shelves : null}/>
      <mesh geometry={nodes.Object_16.geometry} material={materials['.003']} position={[0, 6.676, 0]} scale={[1, 0.111, 1]} material-color={color.Shelves ? color.Shelves : null}/>
      <mesh geometry={nodes.Object_18.geometry} material={materials['.003']} position={[0, 4.121, 0]} scale={[1, 0.111, 1]} material-color={color.Shelves ? color.Shelves : null}/>
      <mesh geometry={nodes.Object_20.geometry} material={materials['.003']} position={[6.244, 3.681, 0]} rotation={[0, 0, -Math.PI / 2]} scale={[0.161, 0.111, 1]} material-color={color.Shelves ? color.Shelves : null}/>
      <mesh geometry={nodes.Object_22.geometry} material={materials['.003']} position={[3.595, 6.252, 0]} rotation={[0, 0, -Math.PI / 2]} scale={[0.161, 0.111, 1]} material-color={color.Shelves ? color.Shelves : null}/>
      <mesh geometry={nodes.Object_24.geometry} material={materials['.003']} position={[6.244, 8.826, 0]} rotation={[0, 0, -Math.PI / 2]} scale={[0.161, 0.111, 1]} material-color={color.Shelves ? color.Shelves : null}/>
      <mesh geometry={nodes.Object_26.geometry} material={materials['.003']} position={[6.244, 13.987, 0]} rotation={[0, 0, -Math.PI / 2]} scale={[0.161, 0.111, 1]} material-color={color.Shelves ? color.Shelves : null}/>
      <mesh geometry={nodes.Object_28.geometry} material={materials['.003']} position={[8.713, 6.252, 0]} rotation={[0, 0, -Math.PI / 2]} scale={[0.161, 0.111, 1]} material-color={color.Shelves ? color.Shelves : null}/>
      <mesh geometry={nodes.Object_30.geometry} material={materials['.003']} position={[3.595, 11.398, 0]} rotation={[0, 0, -Math.PI / 2]} scale={[0.161, 0.111, 1]} material-color={color.Shelves ? color.Shelves : null}/>
      <mesh geometry={nodes.Object_32.geometry} material={materials['.003']} position={[8.713, 11.398, 0]} rotation={[0, 0, -Math.PI / 2]} scale={[0.161, 0.111, 1]} material-color={color.Shelves ? color.Shelves : null}/>
      <mesh geometry={nodes.Object_4.geometry} material={materials['.003']} position={[6.177, 1.465, 0]} scale={[1, 0.111, 1]} />
      <mesh geometry={nodes.Object_36.geometry} material={materials['.004']} position={[-0.629, 1.298, -0.633]} scale={0.128} />
      <mesh geometry={nodes.Object_38.geometry} material={materials['.004']} position={[6.176, 1.298, 0.641]} scale={0.128} />
      <mesh geometry={nodes.Object_40.geometry} material={materials['.004']} position={[6.176, 1.298, -0.633]} scale={0.128} />
      <mesh geometry={nodes.Object_42.geometry} material={materials['.004']} position={[12.817, 1.298, 0.641]} scale={0.128} />
      <mesh geometry={nodes.Object_44.geometry} material={materials['.004']} position={[12.817, 1.298, -0.633]} scale={0.128} />
      <mesh geometry={nodes.Object_34.geometry} material={materials['.004']} position={[-0.629, 1.298, 0.641]} scale={0.128} />
    </group>
  )
});

useGLTF.preload('/living8.glb');

export default Living8 ;
