/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.12 living4.glb
*/

import React, { forwardRef } from 'react';
import { useGLTF } from '@react-three/drei';

const Living4 = forwardRef(({ events, props, action, rotate, color }, ref) => {
	const { nodes, materials } = useGLTF('/living4.glb');
  return (
    <group
			dispose={null}
			{...props}
			{...events}
			ref={ref}
			onClick={action}
			rotation-y={rotate}
		>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.Object_2.geometry} material={materials.m_sofa_up} material-color={color.Sofa ? color.Sofa : null}  />
        <mesh geometry={nodes.Object_3.geometry} material={materials.m_stiches} material-color={color.Stitches ? color.Stitches : null} />
        <mesh geometry={nodes.Object_4.geometry} material={materials.m_sofa_bottom} material-color={color.Seat ? color.Seat : null}/>
        <mesh geometry={nodes.Object_5.geometry} material={materials.m_wood} material-color={color.Wood ? color.Wood : null}/>
        <mesh geometry={nodes.Object_6.geometry} material={materials.m_wooden_legs_metal} material-color={color.Legs ? color.Legs : null}/>
      </group>
    </group>
  )
});

useGLTF.preload('/living4.glb');

export default Living4 ;
