/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.12 living3.glb
*/

import React, { forwardRef } from 'react';
import { useGLTF } from '@react-three/drei';

const Living3 = forwardRef(({ events, props, action, rotate, color }, ref) => {
	const { nodes, materials } = useGLTF('/living3.glb');
  return (
    
    <group
			dispose={null}
			{...props}
			{...events}
			ref={ref}
			onClick={action}
			rotation-y={rotate}
		>
      <group rotation={[-Math.PI / 2, 0, -3.135]}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes.defaultMaterial003.geometry} material={materials['Material.001']} rotation={[-Math.PI / 2, 0, 0]} scale={100} material-color={color.Seat ? color.Seat : null} />
          <mesh geometry={nodes.defaultMaterial002.geometry} material={materials['Material.001']} rotation={[-Math.PI / 2, 0, 0]} scale={100} material-color={color.Foam ? color.Foam : null}/>
          <mesh geometry={nodes.defaultMaterial001.geometry} material={materials['Material.001']} rotation={[-Math.PI / 2, 0, 0]} scale={100} material-color={color.Frame ? color.Frame : null} />
          <mesh geometry={nodes.defaultMaterial.geometry} material={materials['Material.001']} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
        </group>
      </group>
    </group>
  )
});

useGLTF.preload('/living3.glb');

export default Living3 ;
