/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.12 living9.glb
*/


import React, { forwardRef } from 'react';
import { useGLTF } from '@react-three/drei';

const Living9 = forwardRef(({ events, props, action, rotate, color }, ref) => {
	const { nodes, materials } = useGLTF('/living9.glb');
  return (
    <group
    dispose={null}
    {...props}
    {...events}
    ref={ref}
    onClick={action}
    rotation-y={rotate}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.Object_2.geometry} material={materials.TV_FRAME} material-color={color.TV ? color.TV : null} />
        <mesh geometry={nodes.Object_3.geometry} material={materials.TV_Frame} material-color={color.TV ? color.TV : null}/>
        <mesh geometry={nodes.Object_4.geometry} material={materials.wire_177027088} material-color={color.TV ? color.TV : null}/>
        <mesh geometry={nodes.Object_5.geometry} material={materials.wire_229166215} material-color={color.TV ? color.TV : null}/>
        <mesh geometry={nodes.Object_6.geometry} material={materials.TV_Furniture} material-color={color.Furniture ? color.Furniture : null}/>
      </group>
    </group>
  )
});

useGLTF.preload('/living9.glb');

export default Living9 ;
