/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.12 kitchen9.glb
*/

import React, { useRef, forwardRef } from 'react';
import { useGLTF } from '@react-three/drei';

const Kitchen9 = forwardRef(({ events, props, action, rotate, color }, ref) => {
	const { nodes, materials } = useGLTF('/kitchen9.glb');
  return (
    <group
    dispose={null}
    {...props}
    {...events}
    ref={ref}
    onClick={action}
    rotation-y={rotate}>
      <group rotation={[Math.PI / 2, 0, -1.57]}>
        <group rotation={[Math.PI, 0, 0]} scale={0.01}>
          <group position={[1.706, 0, 0]} rotation={[0, 0, Math.PI / 2]} scale={102.702}>
            <mesh geometry={nodes.Retro_Oven_Body_0.geometry} material={materials.Body} material-color={color.Color ? color.Color : null} />
            <mesh geometry={nodes.Retro_Oven_Dial_0.geometry} material={materials.Dial} />
            <mesh geometry={nodes.Retro_Oven_Grill_0.geometry} material={materials.Grill} />
            <mesh geometry={nodes.Retro_Oven_Inside_0.geometry} material={materials.Inside} />
            <mesh geometry={nodes.Retro_Oven_Metal_0.geometry} material={materials.Metal} />
            <mesh geometry={nodes.Retro_Oven_Metal_0001.geometry} material={materials.Metal} />
            <mesh geometry={nodes.Retro_Oven_Metal_0002.geometry} material={materials.Metal} />
            <mesh geometry={nodes.Retro_Oven_Metal_0003.geometry} material={materials.Metal} />
            <mesh geometry={nodes.Retro_Oven_Top_Texture_0.geometry} material={materials.Top_Texture} />
            <mesh geometry={nodes.Retro_Oven_Trim_0.geometry} material={materials.Trim} />
            <mesh geometry={nodes.Retro_Oven_Window_0.geometry} material={materials.Window} />
          </group>
        </group>
      </group>
    </group>
  )
});

useGLTF.preload('/kitchen9.glb');

export default Kitchen9;
