/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.12 kitchen4.glb
*/

import React, { useRef, forwardRef } from 'react';
import { useGLTF } from '@react-three/drei';

const Kitchen4 = forwardRef(({ events, props, action, rotate, color }, ref) => {
	const { nodes, materials } = useGLTF('/kitchen4.glb');
  return (
    <group
    dispose={null}
    {...props}
    {...events}
    ref={ref}
    onClick={action}
    rotation-y={rotate}>
      <mesh geometry={nodes.Object_4.geometry} material={materials.TBL0004_Table}  material-color={color.Color ? color.Color : null} />
    </group>
  )
});

useGLTF.preload('/kitchen4.glb');

export default Kitchen4;
