/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.12 kitchen3.glb
*/

import React, { useRef, forwardRef } from 'react';
import { useGLTF } from '@react-three/drei';

const Kitchen3 = forwardRef(({ events, props, action, rotate, color }, ref) => {
	const { nodes, materials } = useGLTF('/kitchen3.glb');
	return (
    <group
    dispose={null}
    {...props}
    {...events}
    ref={ref}
    onClick={action}
    rotation-y={rotate}>
      <mesh geometry={nodes.Object_8.geometry} material={materials.CPB0002_Cupboard} position={[-0.494, 0.265, 0.338]} material-color={color.Shelves ? color.Shelves : null} />
      <mesh geometry={nodes.Object_6.geometry} material={materials.CPB0002_Cupboard} position={[0.494, 0.265, 0.338]} material-color={color.Shelves ? color.Shelves : null}/>
      <mesh geometry={nodes.Object_4.geometry} material={materials.CPB0002_Cupboard} material-color={color.Box ? color.Box : null} />
    </group>
  )
});

useGLTF.preload('/kitchen3.glb');

export default Kitchen3;
