/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.12 kitchen2.glb
*/

import React, { useRef, forwardRef } from 'react';
import { useGLTF } from '@react-three/drei';

const Kitchen2 = forwardRef(({ events, props, action, rotate, color }, ref) => {
	const { nodes, materials } = useGLTF('/kitchen2.glb');
	return (
    <group
    dispose={null}
    {...props}
    {...events}
    ref={ref}
    onClick={action}
    rotation-y={rotate}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.Object_2.geometry} material={materials.Retro} material-color={color.Back ? color.Back : '#787575'} />
        <mesh geometry={nodes.Object_3.geometry} material={materials.Vetri01} material-color={color.Window ? color.Window : '#808783'} />
        <mesh geometry={nodes.Object_4.geometry} material={materials.Wolf_Cucina_Q1} material-color={color.Box ? color.Box : '#808783'}/>
        <mesh geometry={nodes.Object_5.geometry} material={materials.Wolf_Cucina_Q1}  material-color={color.Stove ? color.Stove : '#808783'}/>
      </group>
    </group>
  )
});

useGLTF.preload('/kitchen2.glb');

export default Kitchen2;

