/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.12 dining1.glb
*/

import React, { useRef, forwardRef } from 'react';
import { useGLTF } from '@react-three/drei';

const Dining1 = forwardRef(({ events, props, action, rotate, color }, ref) => {
  const { nodes, materials } = useGLTF('/dining1.glb')
  return (
    <group
      dispose={null}
      {...props}
      {...events}
      ref={ref}
      onClick={action}
      rotation-y={rotate}
    >
      <group rotation={[-Math.PI / 2, 0, 0]} scale={0.001}>
        <mesh geometry={nodes.Object_10.geometry} material={materials.wire_198225087} />
        <mesh geometry={nodes.Object_11.geometry} material={materials.wire_198225087} />
        <mesh geometry={nodes.Object_12.geometry} material={materials.wire_198225087} />
        <mesh geometry={nodes.Object_13.geometry} material={materials.wire_198225087} />
        <mesh geometry={nodes.Object_14.geometry} material={materials.wire_198225087} />
        <mesh geometry={nodes.Object_15.geometry} material={materials.wire_198225087} />
        <mesh geometry={nodes.Object_16.geometry} material={materials.wire_198225087} />
        <mesh geometry={nodes.Object_17.geometry} material={materials.wire_198225087} />
        <mesh geometry={nodes.Object_18.geometry} material={materials.wire_229166215}  material-color={color.Color ? color.Color : null}/>
        <mesh geometry={nodes.Object_19.geometry} material={materials.wire_224086086} />
        <mesh geometry={nodes.Object_2.geometry} material={materials.wire_087225087} />
        <mesh geometry={nodes.Object_20.geometry} material={materials.wire_224086086} />
        <mesh geometry={nodes.Object_21.geometry} material={materials.wire_224086086} />
        <mesh geometry={nodes.Object_22.geometry} material={materials.wire_224086086} />
        <mesh geometry={nodes.Object_23.geometry} material={materials.wire_224086086} />
        <mesh geometry={nodes.Object_24.geometry} material={materials.wire_224086086} />
        <mesh geometry={nodes.Object_25.geometry} material={materials.wire_224086086}  material-color={color.Chair ? color.Chair : null}/>
        <mesh geometry={nodes.Object_26.geometry} material={materials.wire_224086086}  material-color={color.Chair ? color.Chair : null}/>
        <mesh geometry={nodes.Object_27.geometry} material={materials.wire_224086086}  material-color={color.Chair ? color.Chair : null}/>
        <mesh geometry={nodes.Object_28.geometry} material={materials.wire_224086086} material-color={color.Legs ? color.Legs : null}/>
        <mesh geometry={nodes.Object_29.geometry} material={materials.wire_225143087} material-color={color.Legs ? color.Legs : null}/>
        <mesh geometry={nodes.Object_3.geometry} material={materials.wire_087225087} material-color={color.Legs ? color.Legs : null}/>
        <mesh geometry={nodes.Object_30.geometry} material={materials.wire_225143087} material-color={color.Legs ? color.Legs : null}/>
        <mesh geometry={nodes.Object_31.geometry} material={materials.wire_225143087} material-color={color.Legs ? color.Legs : null}/>
        <mesh geometry={nodes.Object_32.geometry} material={materials.wire_225143087} material-color={color.Legs ? color.Legs : null}/>
        <mesh geometry={nodes.Object_4.geometry} material={materials.wire_087225087} />
        <mesh geometry={nodes.Object_5.geometry} material={materials.wire_087225087} />
        <mesh geometry={nodes.Object_6.geometry} material={materials.wire_198225087} />
        <mesh geometry={nodes.Object_7.geometry} material={materials.wire_198225087} />
        <mesh geometry={nodes.Object_8.geometry} material={materials.wire_198225087} />
        <mesh geometry={nodes.Object_9.geometry} material={materials.wire_198225087} />
      </group>
    </group>
  )
});

useGLTF.preload('/dining1.glb');

export default Dining1;

