/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.12 dining7.glb
*/

import React, { useRef, forwardRef } from 'react';
import { useGLTF } from '@react-three/drei';

const Dining7 = forwardRef(({ events, props, action, rotate, color }, ref) => {
  const { nodes, materials } = useGLTF('/dining7.glb')
  return (
    <group
      dispose={null}
      {...props}
      {...events}
      ref={ref}
      onClick={action}
      rotation-y={rotate}
    >
      <mesh geometry={nodes['1_low_Nabucco_0'].geometry} material={materials.Nabucco} rotation={[-Math.PI / 2, 0, 0]} scale={100} material-color={color.Table ? color.Table : null}/>
      <mesh geometry={nodes['2_low_Nabucco_0'].geometry} material={materials.Nabucco} rotation={[-Math.PI / 2, 0, 0]} scale={100} material-color={color.Stand ? color.Stand : null}/>
    </group>
  )
});

useGLTF.preload('/dining7.glb');

export default Dining7;
