/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.12 dining8.glb
*/

import React, { useRef, forwardRef } from 'react';
import { useGLTF } from '@react-three/drei';

const Dining8 = forwardRef(({ events, props, action, rotate, color }, ref) => {
  const { nodes, materials } = useGLTF('/dining8.glb')
  return (
    <group
      dispose={null}
      {...props}
      {...events}
      ref={ref}
      onClick={action}
      rotation-y={rotate}
    >
      <mesh geometry={nodes.defaultMaterial.geometry} material={materials.acpt_chr_din_batilda_830000024_wood} material-color={color.Stand ? color.Stand : null}/>
      <mesh geometry={nodes.defaultMaterial001.geometry} material={materials.acpt_chr_din_batilda_830000024_fabric} material-color={color.Seat ? color.Seat : null}/>
    </group>
  )
});

useGLTF.preload('/dining8.glb');

export default Dining8;
