/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.12 dining2.glb
*/

import React, { useRef, forwardRef } from 'react';
import { useGLTF } from '@react-three/drei';

const Dining2 = forwardRef(({ events, props, action, rotate, color }, ref) => {
  const { nodes, materials } = useGLTF('/dining2.glb')
  return (
    <group
      dispose={null}
      {...props}
      {...events}
      ref={ref}
      onClick={action}
      rotation-y={rotate}
    >
      <group position={[4.696, 11.294, 4.593]} rotation={[Math.PI, -0.802, Math.PI]}>
        <mesh geometry={nodes.Object_10.geometry} material={materials.PICH}/>
        <mesh geometry={nodes.Object_8.geometry} material={materials.CHOOB} material-color={color.Chair ? color.Chair : null}/>
        <mesh geometry={nodes.Object_9.geometry} material={materials['ZIR_CHARM.001']} />
      </group>
      <group position={[4.476, 11.294, -4.666]} rotation={[0, -0.768, 0]}>
        <mesh geometry={nodes.Object_12.geometry} material={materials.CHOOB} material-color={color.Chair ? color.Chair : null}/>
        <mesh geometry={nodes.Object_13.geometry} material={materials['ZIR_CHARM.001']}/>
        <mesh geometry={nodes.Object_14.geometry} material={materials.PICH}/>
      </group>
      <group position={[-4.723, 11.294, 4.853]} rotation={[-Math.PI, 0.768, -Math.PI]}>
        <mesh geometry={nodes.Object_16.geometry} material={materials.CHOOB} material-color={color.Chair ? color.Chair : null}/>
        <mesh geometry={nodes.Object_17.geometry} material={materials['ZIR_CHARM.001']} />
        <mesh geometry={nodes.Object_18.geometry} material={materials.PICH} />
      </group>
      <group position={[-4.677, 11.294, -4.466]} rotation={[0, 0.802, 0]}>
        <mesh geometry={nodes.Object_4.geometry} material={materials.CHOOB} material-color={color.Chair ? color.Chair : null}/>
        <mesh geometry={nodes.Object_5.geometry} material={materials['ZIR_CHARM.001']} />
        <mesh geometry={nodes.Object_6.geometry} material={materials.PICH} />
      </group>
      <mesh geometry={nodes.Object_20.geometry} material={materials.CHOOB} position={[-1.745, -0.154, -0.711]} rotation={[0.038, -0.222, 3.108]} scale={-1} 
        material-color={color.Table ? color.Table : null}/>
    </group>
  )
});

useGLTF.preload('/dining2.glb');

export default Dining2;

