/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.12 dining4.glb
*/

import React, { useRef, forwardRef } from 'react';
import { useGLTF } from '@react-three/drei';

const Dining4 = forwardRef(({ events, props, action, rotate, color }, ref) => {
  const { nodes, materials } = useGLTF('/dining4.glb')
  return (
    <group
      dispose={null}
      {...props}
      {...events}
      ref={ref}
      onClick={action}
      rotation-y={rotate}
    >
      <mesh geometry={nodes.Object_153.geometry} material={materials.qita} position={[-37.577, 166.896, 2.189]} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_171.geometry} material={materials.qita} position={[17.827, 124.367, -0.268]} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_6.geometry} material={materials.qita} position={[47.94, 66.231, 24.628]} rotation={[-Math.PI / 2, 0, 0]} material-color={color.Body ? color.Body : null}/>
      <mesh geometry={nodes.Object_9.geometry} material={materials.qita} position={[0.125, 66.214, 24.628]} rotation={[-Math.PI / 2, 0, 0]} material-color={color.Body ? color.Body : null}/>
      <mesh geometry={nodes.Object_12.geometry} material={materials.qita} position={[-47.797, 66.231, 24.628]} rotation={[-Math.PI / 2, 0, 0]} material-color={color.Body ? color.Body : null}/>
      <mesh geometry={nodes.Object_15.geometry} material={materials.qita} position={[-73.726, 58.566, 25.14]} rotation={[-Math.PI / 2, 0, 0]} material-color={color.Body ? color.Body : null}/>
      <mesh geometry={nodes.Object_18.geometry} material={materials.qita} position={[73.702, 58.566, 25.14]} rotation={[-Math.PI / 2, 0, 0]} material-color={color.Body ? color.Body : null}/>
      <mesh geometry={nodes.Object_21.geometry} material={materials.boli} position={[0.046, 66.245, 24.68]} rotation={[-Math.PI / 2, 0, 0]} material-color={color.Body ? color.Body : null}/>
      <mesh geometry={nodes.Object_24.geometry} material={materials.qita} position={[-0.097, 54.881, 0.487]} rotation={[-Math.PI / 2, 0, 0]} material-color={color.Body ? color.Body : null}/>
      <mesh geometry={nodes.Object_27.geometry} material={materials.qita} position={[-0.097, 54.171, 0.487]} rotation={[-Math.PI / 2, 0, 0]} material-color={color.Body ? color.Body : null}/>
      <mesh geometry={nodes.Object_30.geometry} material={materials.qita} position={[-0.097, 52.95, 0.487]} rotation={[-Math.PI / 2, 0, 0]} material-color={color.Body ? color.Body : null}/>
      <mesh geometry={nodes.Object_168.geometry} material={materials.qita} position={[26.577, 136.651, -1.122]} rotation={[-Math.PI / 2, 0, 0]} material-color={color.Body ? color.Body : null}/>
      <mesh geometry={nodes.Object_174.geometry} material={materials.boli} position={[20.852, 129.079, -1.105]} rotation={[-Math.PI / 2, 0, 0]} material-color={color.Body ? color.Body : null}/>
      <mesh geometry={nodes.Object_159.geometry} material={materials.qita} position={[13.275, 132.067, -1.122]} rotation={[-Math.PI / 2, 0, 0]} material-color={color.Body ? color.Body : null}/>
      <mesh geometry={nodes.Object_162.geometry} material={materials.qita} position={[26.582, 141.148, -0.66]} rotation={[-Math.PI / 2, 0, 0]} material-color={color.Body ? color.Body : null}/>
      <mesh geometry={nodes.Object_33.geometry} material={materials.qita} position={[-27.561, 66.516, 26.348]} rotation={[-Math.PI / 2, 0, 0]} material-color={color.Body ? color.Body : null}/>
      <mesh geometry={nodes.Object_36.geometry} material={materials.qita} position={[-24.048, 67.518, -0.528]} rotation={[-Math.PI / 2, 0, 0]} material-color={color.Body ? color.Body : null}/>
      <mesh geometry={nodes.Object_39.geometry} material={materials.qita} position={[0.13, 85.581, -0.665]} rotation={[-Math.PI / 2, 0, 0]} material-color={color.Body ? color.Body : null}/>
      <mesh geometry={nodes.Object_42.geometry} material={materials.qita} position={[0.13, 50.119, -0.797]} rotation={[-Math.PI / 2, 0, 0]} material-color={color.Body ? color.Body : null}/>
      <mesh geometry={nodes.Object_45.geometry} material={materials.qita} position={[24.328, 67.492, -0.535]} rotation={[-Math.PI / 2, 0, 0]} material-color={color.Body ? color.Body : null}/>
      <mesh geometry={nodes.Object_48.geometry} material={materials.qita} position={[-72.913, 65.876, -0.265]} rotation={[-Math.PI / 2, 0, 0]} material-color={color.Body ? color.Body : null}/>
      <mesh geometry={nodes.Object_51.geometry} material={materials.qita} position={[-0.028, 65.876, -25.634]} rotation={[-Math.PI / 2, 0, 0]} material-color={color.Body ? color.Body : null}/>
      <mesh geometry={nodes.Object_54.geometry} material={materials.qita} position={[-0.037, 18.358, -0.655]} rotation={[-Math.PI / 2, 0, 0]} material-color={color.Body ? color.Body : null}/>
      <mesh geometry={nodes.Object_57.geometry} material={materials.qita} position={[-0.027, 16.833, 24.365]} rotation={[-Math.PI / 2, 0, 0]} material-color={color.Body ? color.Body : null}/>
      <mesh geometry={nodes.Object_60.geometry} material={materials.qita} position={[-0.005, 115.113, 24.365]} rotation={[-Math.PI / 2, 0, 0]} material-color={color.Body ? color.Body : null}/>
      <mesh geometry={nodes.Object_63.geometry} material={materials.qita} position={[-0.007, 118.674, 0.019]} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_66.geometry} material={materials.qita} position={[-0.007, 117.228, 0.019]} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_69.geometry} material={materials.qita} position={[72.833, 65.883, -0.265]} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_72.geometry} material={materials.qita} position={[72.829, 58.406, -25.553]} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_75.geometry} material={materials.qita} position={[-72.918, 58.406, -25.553]} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_78.geometry} material={materials.qita} position={[-37.518, 173.047, 2.196]} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_81.geometry} material={materials.qita} position={[-37.518, 185.245, 2.196]} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_84.geometry} material={materials.qita} position={[-37.518, 183.73, 2.196]} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_87.geometry} material={materials.qita} position={[-28.622, 173.169, 2.196]} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_90.geometry} material={materials.qita} position={[-37.518, 178.513, 2.196]} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_93.geometry} material={materials.boli} position={[-37.507, 167.213, 2.192]} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_96.geometry} material={materials.qita} position={[-37.504, 163.658, 2.207]} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_99.geometry} material={materials.qita} position={[-37.518, 162.65, 2.196]} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_102.geometry} material={materials.qita} position={[-37.518, 160.411, 2.196]} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_105.geometry} material={materials.boli} position={[-37.518, 141.051, 2.196]} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_108.geometry} material={materials.qita} position={[-37.518, 122.077, 2.196]} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_111.geometry} material={materials.qita} position={[17.827, 120.876, -0.267]} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_114.geometry} material={materials.qita} position={[-0.325, 8.276, 14.5]} rotation={[-Math.PI / 2, 0, 0]}  material-color={color.Body ? color.Body : null}/>
      <mesh geometry={nodes.Object_117.geometry} material={materials.qita} position={[41.003, 8.32, -2.966]} rotation={[-Math.PI / 2, 0, 0]} material-color={color.Body ? color.Body : null}/>
      <mesh geometry={nodes.Object_120.geometry} material={materials.qita} position={[-0.037, 8.276, -0.655]} rotation={[-Math.PI / 2, 0, 0]} material-color={color.Body ? color.Body : null}/>
      <mesh geometry={nodes.Object_123.geometry} material={materials.qita} position={[-41.657, 8.32, -2.966]} rotation={[-Math.PI / 2, 0, 0]} material-color={color.Body ? color.Body : null}/>
      <mesh geometry={nodes.Object_126.geometry} material={materials.qita} position={[0.967, 33.523, 6.5]} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_129.geometry} material={materials.qita} position={[0.967, 24.747, 6.5]} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_132.geometry} material={materials.qita} position={[-37.518, 140.513, 2.196]} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_135.geometry} material={materials.qita} position={[-37.518, 121.485, -4.053]} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_165.geometry} material={materials.qita} position={[13.271, 136.447, -0.66]} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_138.geometry} material={materials.qita} position={[-37.518, 173.169, -6.7]} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_141.geometry} material={materials.qita} position={[-46.414, 173.169, 2.196]} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_144.geometry} material={materials.qita} position={[-37.518, 173.169, 11.091]} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_147.geometry} material={materials.qita} position={[21.322, 66.516, 26.348]} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_150.geometry} material={materials.qita} position={[28.008, 66.516, 26.348]} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_156.geometry} material={materials.boli} position={[-37.518, 166.793, 2.224]} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_177.geometry} material={materials.qita} position={[0.306, 116.525, -0.54]} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_180.geometry} material={materials.boli} position={[26.577, 129.002, -1.105]} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_183.geometry} material={materials.boli} position={[13.275, 126.785, -1.085]} rotation={[-Math.PI / 2, 0, 0]} />
    </group>
  )
});

useGLTF.preload('/dining4.glb');

export default Dining4;